### ISSUE TITLE
Is aircraft search negation possible?

### ISSUE THREAD

**Issue by pballer2oo7** [ericberman/MyFlightbookWeb#1088]
**As a** pilot **I'd like to** search for all aircraft _except_ these few **so that I** can have a "All U.S. registered aircraft" saved search that doesn't require I modify my search every time I fly a new U.S. registered aircraft.

Is this already supported?

**Comment by ericberman** [comment]
Not explicitly, but there are a few ways you can do this:
  * When you do a search, do select-all in the aircraft and then uncheck the ones you don't want.  But that obviously misses your point of "modifying your search when you fly a new aircraft"
  * Or, put a tag in the *private* notes for the non-US aircraft in your account (private notes are searched, public notes are not) like "#NONUS#".  Then you could search for "-#NONUS#", which will exclude anything with "#NONUS#" in the flight (including aircraft private notes).  Nothing magic about "#NONUS#", I just often recommend using a "#" as a prefix/suffix to avoid false positives/negatives when searching.

What's the scenario you're trying to address here?  There may be other ways to handle it besides looking for aircraft with a certain country registration...

**Comment by pballer2oo7** [comment]
The private notes tag sounds like a workable solution. Thanks!

The scenario: I have an FAA and an EASA logbook. When pulling reports, showing experience, or crosschecking totals with paper logbooks or employer records it's convenient to only show one or the other authorities' flight times in MFB.

**Comment by ericberman** [comment]
OK, but if you fly an N-number in Europe or a European aircraft in the US, what's the right thing to do?

**Comment by pballer2oo7** [comment]
That's a good question. When I fly N-numbers in Europe I'm flying under U.S. licensing authority so it goes in the U.S. logbook, not the EASA one.

**Comment by ericberman** [comment]
Well, either way, the "all but" option isn't a bad idea...

**Comment by pballer2oo7** [comment]
Copy that. I've been using MFB for awhile and just today realized it's on GitHub. I've cloned it and am familiarizing myself. I'll try to add the feature when able and send you a PR.

In the meantime, I private note tagged all my European tails like you suggested and it's working great. Thanks for the help!

**Comment by ericberman** [comment]
I'm going to won't-fix this.  I realized there's an easy way to do this (a bit of a hack, I admit, but fully supported): if you want to exclude N12345 and N23456, you can use a search term of "-N12345 -N23456".

My main concern with adding new conjunctions (AND, OR, NOT) is ensuring that nothing breaks on the mobile apps.  So if you did a saved search, making sure that it gets submitted correctly if the mobile apps don't know about the conjunction.  I can update the apps, it's not really a problem, but there's versioning to deal with and I'd rather not.  The text solution is an elegant way to ensure round-trip compatibility.
