### ISSUE TITLE
Edit diff for simulated instrument time says "added IMC"

### ISSUE THREAD

**Issue by rlazarus** [ericberman/MyFlightbookWeb#1219]
I edited a flight to add 0.3 of simulated instrument time. It now shows a diff on the main logbook page -- I expected the diff to say

> This flight has been modified since originally saved.
> * Added: Sim. Instrument (0.3)

but it actually says

> This flight has been modified since originally saved.
> * Added: IMC (0.3)

**Comment by ericberman** [comment]
I've merged the fix into the master code base, but it'll be a couple of days before I can update the site

**Comment by rlazarus** [comment]
Thanks for the quick review -- and for running the service!
