### ISSUE TITLE
Request: "Repeat and Reverse" for a Pending Flight

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#1335]

**Comment by ericberman** [comment]
This is really a scenario?

**Comment by zartom** [comment]
I think it is. I'm inputting my monthly schedule in advance, consisting of round trips with the same crew staying for the return. It helps to reverse the route and use all the names of the entire crew in the new entry

**Comment by ericberman** [comment]
OK; I already coded this yesterday (pretty trivial), will be live the next time I update the website.  Or were you asking for this on iOS/Android?  If so, please add this issue to those repositories (github/ericberman/myflightbookios and github/ericberman/myflightbookandroid).

**Comment by zartom** [comment]
It was for the web, but I could see myself do it on a mobile device

בתאריך יום ו׳, 15 בנוב׳ 2024, 18:37, מאת Eric Berman ‏<
***@***.***>:
