### ISSUE TITLE
IACRA Class Totals Missing Dual Received

### ISSUE THREAD

**Issue by joelthompson** [ericberman/MyFlightbookWeb#1363]
Thanks for an awesome product! I just filled out an IACRA application and the IACRA report was incredibly helpful. It just presented everything I needed to fill in as I needed it, except at the very end. IACRA asks for class totals broken down by PIC, SIC, and dual received. The MyFlightBook IACRA report gives PIC and SIC by class, but not dual received. Fortunately it's easy for me to calculate this as I only have a single class logged (ASEL) and so just entered my total dualr received time, but adding dual-received in the class total breakdown at the end would make this perfect.

**Comment by ericberman** [comment]
Thanks for the kind words!
Dual received = Instruction Received (two ways of saying the same thing).  So, umm...?
![image](https://github.com/user-attachments/assets/24041f66-5ff3-47da-ae57-dd22b195f33b)

**Comment by joelthompson** [comment]
That's category (airplane), not class (ASEL/AMEL/ASES/AMES). Instruction received is missing here.
![Screenshot_20241212-105102](https://github.com/user-attachments/assets/908694ad-3618-48f2-aa3c-253d0e6d2e38)

**Comment by joelthompson** [comment]
And here is the relevant section of my IACRA application where it asks for class totals including instruction received.
![Screenshot_20241212-112143](https://github.com/user-attachments/assets/24fedeb8-9ac0-454f-8156-32109aa3d06d)

**Comment by ericberman** [comment]
Gotcha.  That's new from when I originally implemented this 10+ years ago; never noticed that.  I do have the other class totals there (see below for my personal totals) but indeed I don't have instruction broken down by class; that should be pretty easy to add.  Thanks for clarifying!
![image](https://github.com/user-attachments/assets/b760b5d5-a1dc-449d-813b-c83ae3f6ad04)
