### ISSUE TITLE
Can’t filter totals by sub-type

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#1368]
Steps to reproduce:
Under totals, go to search
Under Flight Aircraft make/model search a subtype (for example 787-**8**) and apply 
Totals (number of hours, approaches, etc.) show for that subtype, but when clicking to see the filtered flights it will show for every subtype type in the family)

**Comment by ericberman** [comment]
This will likely have to wait until I'm home late next week.  It appears that I did this deliberately - that if the search contains a model specification AND a type rating specification, then I do an "OR" on them rather than an "AND".  It's the "OR" here that is causing the issue.  I'm reluctant to change this without remembering the rationale for having done it this way because I don't want to break that scenario.


Here are the relevant lines of code in FlightQuery.cs (around 1180): 

                // Splice the type query into the models query as an OR - i.e., matches EITHER model OR typenames.
                szModelsTextQuery = String.IsNullOrEmpty(szModelsTextQuery)
                    ? szModelsTypeQuery
                    : String.Format(CultureInfo.InvariantCulture, "({0}) OR {1}", szModelsTextQuery, szModelsTypeQuery);

...

            // If both ID's and free text are specified, OR them.  Otherwise, just do whatever is specified
            if (!String.IsNullOrEmpty(szModelsIDQuery) && !String.IsNullOrEmpty(szModelsTextQuery)) 
            {
                AddClause(sbQuery, String.Format(CultureInfo.InvariantCulture, "(({0}) OR ({1})) ", szModelsIDQuery, szModelsTextQuery));
            }
            else
            {
                AddClause(sbQuery, szModelsIDQuery);
                AddClause(sbQuery, szModelsTextQuery);
            }

This wasn't accidental, but I don't remember why.

**Comment by ericberman** [comment]
Do also note that the operation you are doing (clicking on the type-rating total when you've already filtered by a model) is a no-op anyhow.  By definition, if your search was for B-787-8, then all of the flights included in the totals you are seeing already are B-787-8's and have a B-787 type rating requirement.  Specifying that you want to see totals for flights that are in B-787-8's AND  require a B-787 type rating is redundant with simply totals for flights that are in B-787-8's..

**Comment by ericberman** [comment]
I'm going to close this as "won't fix" for two reasons:
a) I still haven't quite figured out why I did "OR" between a model specification and a type specification, so I'm not sure what I'd break, but more importantly...
b) if you want to see the flights by model, go to recent flights and do the initial search for 787-8 there, not via totals.  That gives you exactly what you want.  When you click on the required type rating in totals, that's...a request for flights with that type rating.  So I'm not quite sure why you'd start in totals if your goal is to see the relevant flights.
