### ISSUE TITLE
New achievement ideas: records

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#255]
Longest flight, most landings, etc.  Need to break a threshold first, though, for it to be meaningful.

**Comment by ericberman** [comment]
Recent Achievements already do this; just added them to achievements page.

**Comment by KayRJay** [comment]
It would be nice to have on the Achievements page the following

- Longest streak **without** consecutive flying days
- Most landings on one day
- More Milestones -- maybe you already do these?
   - 100 hours, 500 hours, 1000 hours
   - 50 flights, 100 flights, 500 flights, 1000 flights
   -  10 landings, 50 landings, 100 landings
- A list of possible Achievements
- A custom date range

 What is the little box next to the date drop-down menu under flying stats?

**Comment by ericberman** [comment]
Longest streak without flying is an interesting one, as is most landings in a day.
I already the achievements around flights and hours; I've always deliberately NOT published a list of possible achievements - I want it to be more like a video game where you earn a badge for killing 100 nazis or something like that; it's more fun to stumble on them. 

Could do a custom date range (heck, I could do full query capabilities), but I thought this would be very simple and would capture the most common scenarios.  E.g., I understand wanting to know "hey I flew 45 days last year", but I have a much harder time getting why someone would care about "I flew 3 days between July 5 and July 21".

If you hover over the box next to the date drop-down you'll see that clicking it will copy your stats to the clipboard for you.  Makes it easy to share!

**Comment by KayRJay** [comment]
> On Jan 3, 2020, at 6:31 PM, Eric Berman <notifications@github.com> wrote:
> 
> Longest streak without flying is an interesting one, as is most landings in a day.
> 
Yes, thanks.  I hope you’ll add those.
> I already the achievements around flights and hours; I've always deliberately NOT published a list of possible achievements - I want it to be more like a video game where you earn a badge for killing 100 nazis or something like that; it's more fun to stumble on them.
> 
Nah … I see the possible achievements as a GOAL. I want to know what’s possible to achieve.  This isn’t a GAME … it's a PROCESS of becoming a qualified pilot (or achieving something else important).  The whole idea here is NOT a game.
> Could do a custom date range (heck, I could do full query capabilities), but I thought this would be very simple and would capture the most common scenarios.
> 
Sure, no big deal.  But just for completeness and consistency with the rest of the UI.
> E.g., I understand wanting to know "hey I flew 45 days last year", but I have a much harder time getting why someone would care about "I flew 3 days between July 5 and July 21".
> 
Why not  I might well want to know how many flights I took in the summer vs. the winter, for example.
> If you hover over the box next to the date drop-down you'll see that clicking it will copy your stats to the clipboard for you. Makes it easy to share!
> 
I tried that, but I “see” nothing.  There is no visual indication that anything happens.  Maybe if it said “Copy to clipboard”, but I can do that just by selecting the text and Command-C.

**Comment by KayRJay** [comment]
Very minor point why "custom dates" would be useful ...

Stats
- Since I first solo'd
- Stats since achieving a specific milestone (e.g., flights since first 100)
- Stats since gaining a rating
- etc.

And, as mentioned elsewhere, it could be interesting to get stats for certain months (multi-select) without respect to a year.   A user might be interested only in winter flights, or a pilot might spend part of the year in different locations.

etc.

No big deal here, but I just thought I'd record these additional reasons.

**Comment by KayRJay** [comment]
More milestones (or achievements):
10, 50, 100 airports visited
10, 50, 100 countries visited
Highest altitude achieved

**Comment by ericberman** [comment]
Great suggestions, but nothing to do on these:
 * # of airports visited is already an achievement
 * I don't have country data - that can also be sensitive.  (E.g., if you fly from Taipei to Beijing, there's no way to count that without pissing someone off).  (I *do* however do continent checks...)
 * I also have no altitude information for a flight or elevation information for airports.
 * You can get most frequently visited airports already by going to the Visited Airports page and sorting by Visits.  No reason to limit to the top 5.

**Comment by KayRJay** [comment]
Interesting point about data sensitivity.  But if I’m the pilot, I know I flew between places.  The Achievements are visible only to the pilot who logged the flights.

I’m still working on an issue to add lat/long, elevation, etc. to airport info.   You do have a flight property for “Maximum altitude”.

**Comment by ericberman** [comment]
Indeed, I do have Maximum Altitude (it's glider pilots, mostly who use that).
Anyhow, this issue is getting loaded with a gajillion things.
Current commit addresses the key things and adds:
 * Longest non-flying streak in period
 * Most landings in a day
 * Custom dates
 * Pop-up (then fade) UI indication of clicking the copy button.  By the way - the reason I have a copy link instead of just control-c is twofold: (a) select+copy will pick up things like the drop-down and (b) it picks up formatting - including hyperlinks - that won't work if you send them to others (because it links into your account).  The idea is that you want to copy to clipboard and then share it on facebook or in email or ....  The copy button lets you share that "cleanly".

**Comment by KayRJay** [comment]
Great, thanks.   If the issue comes up again, it's because I've used the feature and really miss some of the other ideas ...
