### ISSUE TITLE
Should do a competition chart and a full "About MyFlightbook" page that includes it.

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#269]

**Comment by ericberman** [comment]
here's Foreflight comparison:
-	Custom currencies
-	Custom deadlines
-	Aircraft maintenance
-	Deadlines tied to aircraft
-	Shared flights
-	Vastly more ratings progress
-	Vastly more currencies, including military, EASA, Canada
-	Currency/totals emails and stats
-	Cloud backup
-	Bulk Edit
-	CloudAhoy integration
-	Flight Templates
-	Android
-	Custom airports
-	Visited airports
-	Achievements/badges
-	Attach videos to flights
-	Autofill from GPX 
-	Analysis/graphs
-	Starting Totals
-	Flying clubs
-	Customizable totals
-	Saved queries
-	Multiple print options and layouts
-	Full functional on website (actually more!)
-	FREE

**Comment by KayRJay** [comment]
Nice!  Features that seem to be missing in the above:

- iOS
- Import flights from other logs
- Consistency checks
- Departure and takeoff indications
- Profiles and templates of properties
- Can record over xxxx properties of flights, aircraft, pilots (?)
- Can capture GPX during a flight

Might also be helpful to list these features in related groups.

This also addresses issue #524.   Thanks!

**Comment by ericberman** [comment]
Actually, take a look at https://docs.google.com/spreadsheets/d/1nTIMxMVVU88Y1J35QRUwc5oJAOzUCdMNamcE6NcZtSU/edit?fbclid=IwAR155nd3JCKVU3MNzHyicjbK1KVh-LuVyQUK-sN8D8BVo8DQGR-OX4BzZ-A#gid=0.  What I've implemented draws from this.

**Comment by ericberman** [comment]
this is now live.  Click on "About MyFlightbook" in footer to get to it.

**Comment by KayRJay** [comment]
Nicely done!

I see only Foreflight, but because the heading, it seems I should be able to compare to something else.  Do you plan a drop-down or < and > arrows to scroll between competitors? Have you just not loaded another comparison?   The data appear to be in the spreadsheet ...

Also, minor nit ... wrt Foreflight, it's a "minimum" not "minimal"(aka "marginally small") subscription.

**Comment by ericberman** [comment]
good catch on minimum.

I only have foreflight at the moment because (a) it's my main competitor these days, and (b) it's the one I have the most complete comparitive information for.  Mcc is next most complete, but I don't think it's as significant a competitor, and it's focused on Europe too.
