### ISSUE TITLE
ft=Add and adding a flight should take you back to ft=add for another flight.

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#308]
Makes adding multiple flights easier.

**Comment by KayRJay** [comment]
These things will make adding multiple flights easier (without sacrificing ease of use to add one flight):
In addition to ADD FLIGHT, have ADD/NEW (to stay on the same page)
ADD/NEW would clear all fields, and advance the flight date by one day
CANCEL (or CLEAR or RESET) would clear all fields
