### ISSUE TITLE
Warn when navigating away from partially filled-in flight?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#311]

**Comment by ericberman** [comment]
Finally got around to looking at this.  I need to create a table of "here are the original values for each field" when the page is initialized; when the page is unloaded ("onbeforeunload" window event), I then look at each of the data entry fields and compare its value to what's in the table.  If they're the same, great; if any is unchanged, then I prevent the default behavior causing the browser to ask if I'm sure about navigating away from the page.  Simple enough, I implemented it, and it works...as far as it goes; if this were just a couple of fields to check, I could do it reasonably reliably.

But alas It's actually crazy complicated to get this to a state where I'm willing to deploy this, for a variety of reasons:
 * A number of the controls on the page are dynamic (e.g., properties), so they can be added and not show up in the table or be deleted and then the table will reference fields that no longer exist.   Doing incremental changes to the table is hard because it means that knowledge of and access to the table must be distributed throughout the code, which makes for highly fragile and unmaintainable code.  So I have a choice of a partial feature (that warns about some changes but not others) or spaghetti code.
 * In a similar vein, the flight editing control does not actually have access to each of the underlying fields.  It has access to some, but others are delegated and abstracted into other controls.  E.g., the flight editing control embeds a property-editing control (which handles properties) and a flight-times control (which handles hobbs/engine/flight times), and an image-handling control, etc.  So to properly handle most edits, I would need every sub-control to either expose all of its fields (breaking abstraction) or create the spaghetti of having them all know about and access the "original values" table.  Either is not just a nightmare to implement, but is incredibly fragile and hard to maintain.
 * In the client javascript, http postbacks are indistinguishable from http gets.  And the system uses postbacks all over the place: you have a postback when you pick a different aircraft, when you add a property to the form, etc.  There are some hacks I've found on the internet to distinguish a postback from a get, but none are truly reliable.  As a result you get prompted to confirm the page excessively - e.g., when choosing an aircraft from the list; obviously, that's not acceptable behavior.
 * Worse than that - the "Add flight" form is on the same page as totals, currency, analysis, etc., which not only can cause postbacks, but which hide the "Add flight" form while they are visible.  So if you start to edit a flight and then view currency or similar, then the partially filled-in flight is still on the page and still partially filled in, but is simply collapsed (all of the expanding/collapsing is done client-side, no navigation occurs).  As a result, if you navigate away, you're prompted to confirm that you want to navigate away from unsaved changes, but alas you can't see anything unsaved because the new-flight form is collapsed!
 * A further complication is watermarks: many fields have watermarks (e.g., "0.0" for decimal fields).  If I properly abstract out the "did anything change" code, it just sees html text edit boxes.  So if a field's original value is 0, then the html value is its watermark ("0.0" or "00:00" or "0,0" or others, depending on locale and hh:mm preference), but if you click in the field, the watermark goes away.  So you'd have the "original value" in the table being, say, "0.0", but its current value due to the click is "" (empty string), so that would be a change even though nothing has changed.  There are workarounds, to this, but with everything else, doing so would be a hack upon a bunch of other hacks, and I fear that I would in the future be continuously adding workarounds, implementing browser compatibility fixes, and breaking this when I perform unrelated changes.

I think this is a good feature idea, but both the up-front and ongoing costs are going to vastly outweigh the benefit on this.

**Comment by KayRJay** [comment]
From a naive user's point of view, it would seem entering a value in any field (or clearing a value) would simply set a globally accessible variable to stay "something's new".   Every control must know when the user enters a value, even if that value is the same (or logically the "same") as the previous value.   Treating that case as "something's new" (even if it isn't really) wouldn't be burdensome to the user, it seems.   

But maybe that's not how HTML data entry works.  (I'm just assuming that if the cursor is in a field, and is moved out, that is observable to the code somehow.)

I actually don't understand all the explanation above, but I respect your decision.  Thanks for considering it.

**Comment by ericberman** [comment]
What you describe above was (almost) actually exactly my initial thinking about how to do this, but it actually doesn't change much above.

You absolutely **must**, IMO, distinguish "is different from previous value" from "something's new."  For two reasons: (a) because of the watermark in decimal fields, simply clicking in an empty field generates a change event, and (b) false-positive warnings are an awful user experience.  The warning provided by the browser (most no longer allow you to specify your own message; they simply allow you to indicate if a generic "The page is asking if you want to leave" message should be shown) doesn't give any indication of what changed where, so it's incredibly scary to see a message like that and have no idea what you may have changed; if you didn't actually change anything, it's frustrating to hunt unsuccessfully for it.  I think false positives here are far worse than false negatives.  So you have to have a "I'm dirty" variable for each field.  It's actually a bit worse than that, because the set of controls on the edit flight page are so dynamic: if you add a control (e.g., add a property) and then remove it, you're not dirty, but if you remove a control that had a value, you're not, but if you remove a control that didn't have a value, then you're also not dirty...

I ultimately gave up on this "bottom up" approach largely because the "globally accessible variable" can't be in memory (javascript variables don't persist from page-load to page-load), so it needs to be put into the page state itself somewhere.  That means that low-level controls like edit boxes need to know about the structure of their host page (in order to find where to put their variable), which exceedingly bad design - highly brittle, hard to maintain, easy to break.  

That's why I tried a top-down approach: I have a snapshot of the state and on navigate away I can say "is anything different", and none of the lower level controls need to know anything.  So it's a better design from that perspective.

But either approach still suffers all of the issues I identified above.  If this were a simple form without a bunch of postbacks, without other stuff on the page that can hide the form, without dynamic controls, without multiple layers of abstraction, etc., then it would be pretty easy to do.

**Comment by KayRJay** [comment]
Thanks for the detailed explanation.
