### ISSUE TITLE
Templates: list loses scroll position  after each drag/drop

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#319]
At very least, can we do everything with ajax so that there's no postback and hence no reset of scroll position?  Second half of suggestion is to allow for multi-select drag and drop to minimize number of required drag operations.  Or have an ">>"  and "<<" button that moves everything from left to right or vice versa?

**Comment by KayRJay** [comment]
Similar comments apply to the situation of adding properties to a flight itself, on the main Add Flight page.   

Other ideas for simplifying use and selection of properties:
- Be able to "jump to" a property via an alphabet on the side, like contacts on an iPhone
- Have collapsable categories/groups of properties, with the properties alphabetized within them

Also a vote for multi-select and no reset of scroll position at least (though  << and >> seem less useful).

**Comment by KayRJay** [comment]
By the way, there is no reason a given property couldn’t be in two groups for this purpose.  For example Night landings could be under both Night and Landings, even tho there is only one property that could be added or removed from a template or flight.

**Comment by ericberman** [comment]
Fixed the bug at hand by eliminating the postback.

Alphabet on the side idea is separate from the issue here, but doesn't work well in this scenario for two reasons: (a) it requires a fair amount of real estate (either horizontal or vertical), but more importantly, (b) it's really just first letter, which doesn't help all that much.  E.g., if you're searching for "Night Takeoffs", do you want "N" or "T"?  Spins are under "M" for "Maneuvers: Spins", etc.  The search/filter tool, I think, works far more effectively to find what you want, particularly if it's named differently from what you expect.

On the categories/groups: also off topic for this issue, but the main problem with that is simply devising a taxonomy that has good coverage.  Some are easy: takeoffs, landings, approaches, night vision, maneuvers.  But then there is a very long tail of "one-off" properties that don't neatly fit into any of the broader categories.    E.g., what categor(ies) would "Instructor On Board" be under?  

I'm not opposed to doing categories/groups, but with templates to handle groups of properties, i'm not sure categories/groups would buy you for ad-hoc properties.
