### ISSUE TITLE
Add option to exclude aircraft when printing 

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#320]

**Comment by KayRJay** [comment]
Just to save column width.

**Comment by ericberman** [comment]
So literally no tailnumber or make/model?

Note: some printing templates are crazy prescriptive (EASA) such that they preclude customization, but most others can be customized.

**Comment by KayRJay** [comment]
Right … the idea is that I might add an additional column or two and want to save space.  Just for my own, not regulatory purposes.

**Comment by ericberman** [comment]
OK, so I just mostly coded this up, but I'm going to discard it:
 * CASA, SACAA, EASA, and Canada layouts are very prescriptive, with a lot of "thou shalt".  So the option would not be available in these layouts.
 * Even in the US, [61.51(b)(1)(iv)](https://www.law.cornell.edu/cfr/text/14/61.51) makes it super clear that make/model and registration are required.
 * The "Portrait" layout (probably the most efficient of the layout) doesn't gain anything from elimination of it.

The main reasons people print out or create PDFs is for a backup, for job interviews, and for checkrides.  In all of those cases, having the tail number and model is not optional.

So I think I'm going to punt on this.
