### ISSUE TITLE
Turn off certain times for adding new flights

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#321]
For my new, pre-solo, only VFR training, I'm not interested in entering (or skipping over) the following times: Simulated instrument, IMC, Ground Sim., PIC.  It would be helpful to be able to exclude them from entry.   These could all be suppressed under "Advanced" or "Show More" ...  This would make the entry screen a little more compact.

Now that there are templates, which permit including some time-valued properties, perhaps all/most of the times used under General Flight Info should be controlled by templates?    In that case, you might need to add some properties that are not now user-selectable, but are hard-coded under General Flight Info.

**Comment by ericberman** [comment]
Even in VFR training, you *will* use simulated instrument and PIC (when you do solo).  These are not advanced.  I left these there by default for three reasons: 
(a) every logbook on the planet has them, so there is an expectation that they will be there.
(b) Every pilot - airplane, helicopter, glider, balloon - will eventually use them if they get a rating.  The only ones you aren't required to use at some point in getting a rating are ground sim (though it's crazy common) and IMC (if you stop at VFR).
(c) They are specified regulatory by some governing bodies like EASA.

So if I made them optional, I'd absolutely leave them turned on by default (why make someone hunt for them?), so you'd have to turn them off only to turn them on again a little while later in your training.  Doesn't seem like I'm really solving a problem in that scenario.

Note that SIC and CFI *can* be turned on/off; these are things that only apply if you have certain ratings or do certain types of flying, so if you never get your CFI rating, you'll never hit that.
