### ISSUE TITLE
Editing multiple flights from Add/Edit Flight page

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#322]
When manually entering several flights, it is easy to make mistakes.   This can require editing multiple flights.  For example, you might enter some parameters for one flight incorrectly on another.  Then both flights need to be edited.

It would be helpful to have the ability to edit several flights from the same page without going to the summary list.   PREVIOUS and NEXT buttons would make it easy to review and edit the flights on either side of a just entered or edited flight.

**Comment by ericberman** [comment]
I think the way to do this is to have the edit flight page return to the details page after editing.  If I simply have next/prev, then it's ambiguous if I should silently commit or silently discard any changes.  But it's fairly easy to have the edit page return to the details page.  I really don't want to put the edit control on the details page because it's a heavy enough page as it is, and the edit control is fairly heavyweight.  So you'd click "Update" (or Cancel) on the flight you were editing, and then you could press next/prev.

**Comment by KayRJay** [comment]
This comment addresses UI issues: which page is displayed when navigating to next or previous, and how the user chooses between saving and saving with navigation.

The meaning of NEXT and PREVIOUS in this editing scenario is discussed in issue #359 (but should have been posted here).

Which page to display ...

It is unhelpful to go to the details page if the user intends simply to a single flight, as he doesn't need to review the details of the flight he just edited.  It's best to go back to the logbook listing as it works now.  In this scenario, most likely the user has selected a single flight to edit from the logbook list, rather than a search, so returning to the list is what would be expected.

When the user intends to edit multiple flights, one at a time, displaying the details page after the edits are saved is ok, but it requires moving the cursor to the top of the page and pressing < or >.  

The better alternative, it seems, is to refresh the Edit page, with data fields filled in from the relevant flight.    As we've discussed in email, NEXT and PREVIOUS most naturally refer to the next flight in date/time, not the next flight in a search result set.   

User interface ...

The UI could include two new buttons, so the bottom of the page becomes
         CANCEL    SAVE      SAVE/NEXT    SAVE/PREVIOUS

Another idea is to use a down-arrow in a box adjacent to the button ...  SAVE ↓ ... to reveal these options:

   SAVE ... and return to list
   SAVE ... and review details of this flight
   SAVE ... and edit PREVIOUS flight (mm/dd/yy)
   SAVE ... and edit NEXT flight (mm/dd/yy)

The first two are probably not necessary, as pressing SAVE (not the down-arrow)  would take that action, and the second action isn't really necessary.
