### ISSUE TITLE
ALL, ANY or NONE for search parameters in a group

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#323]
New search queries that may not be possible now could be posed if the user could specify whether all of the parameters in a search group are ANDed, ORed or (AND NOTed) together, resulting in flights that match ANY, ALL or NONE of the chosen parameters.  (This doesn't apply to mutually exclusive parameters of course.)

A possible UI:
- Flight had *choice* of the following characteristics: (Click to Show):
- Flight visited *choice* of these airports (Click to Show):
- Flight was in *choice* of these categories/classes: (Click to Show):
- Flight aircraft had *choice* of these aircraft characteristics (Click to Show):
- Flight had *choice* of these properties: (Click to Show):

The item *choice* would be one of these words: ALL, ANY, NONE.   They would be blue underlined, like a link, but on user clicks would cycle between them, both visually and to control how the parameters in that group are used in the search query, which would be in a formulation like these (where andor is either AND or OR):

SELECT …. A AND NOT B
SELECT … (A andor B andor C) AND NOT (D OR E OR F).

**Comment by KayRJay** [comment]
Of course I should clarify:   ALL = AND, ANY = OR, and NONE = AND NOT.   The fist sentence above implied AND = ANY.

**Comment by ericberman** [comment]
To capture Issue #325 here as well: would be good to be able to do this at the individual item level.

**Comment by ericberman** [comment]
Additional issues to address in any expansion here beyond the simplest group-level:
 * FlightQuery object needs to be able to capture this and serialize it.
 * Any such changes to FlightQuery need to be backwards compatible with iOS/Android and survive a roundtrip
 * Need to figure out how the iOS and Android interface would handle this (small screen, touch, etc.)
 * The "filters" UI where you see applied filters and can click to remove them becomes more complex if we do anything beyond doing this at the group level.  One tradeoff there could be to still capture the filter at the group level, even if a group's individual criteria mixes AND/OR/NOT, since groups are still always AND'd together.
 * Another thought is to offer an "Advanced" mode where you write out the query in text.  Can be fully flexible, but also difficult - besides a ton of code, it requires error handling, and a clear way to define search terms.

Probably more, but those come to mind right now.

**Comment by ericberman** [comment]
OK - if you add "conj=1" to the URL of a page with a search form, you'll get ALL/ANY/NOT for flight characteristics and for properties.  I'm leaving this hidden for now while I incorporate support on iOS/Android, at which point I'll expose it all.

Note that I did NOT do this for other groups either because (a) AND makes no sense (e.g., searching for flights that are in aircraft A AND in aircraft B will always yield nothing, since a flight can only be in one aircraft), and (b) NOT can be achieved by clicking "SELECT ALL" (Aircraft, models, category/classes) and unchecking the ones you don't want, or (c) the choice is inherently mutually exclusive (engine type, dates.)  I'm also leery of adding it to airports because airports are inherently squishy: e.g., "KSFO" vs. "SFO", "OGG" for Maui vs. "PHOG" - you want to allow multiple names for an airport.

**Comment by KayRJay** [comment]
Wow, that’s great!    Thanks for implementing yet another of my suggestions/requests!   I look forward to trying it … but I don’t know how to add “conj=1” to the URL of search pages.  (I’m no HTML expert!).  

Delaying the implementation of this feature until iOS and Android have it makes perfect sense.  What are you planning for the UI?

I want to follow on a bit on the use of ALL/ANY/NOT for the other types of groups of criteria … sorry for the length of this note, but I thought quite a bit about things.  I hope you’ll find time to consider and respond to the points below.

Thanks again.  Regards,

Ken

================

First, to restate the rationale for being able to chose how the various criteria are combined.   Currently, I believe MFB treats all criteria groups in the same way … the choices are OR’d, meaning that flights will be found if ANY of the specified criteria are present for the flight.   This is true even though the wording varies between groups:

Flight had the following characteristics
Flight visited any of these airports
Flight was in one of these aircraft
Flight was in one of these Makes/Models
Flight was in these categories/classes
Flight aircraft had these aircraft characteristics
Flight had one of these properties

You may have chosen different wordings because you were thinking of a single flight (which could only be in one aircraft, model or category/class for example).   Therefore it makes sense to say “one of” in those cases, even though MFB OR’s all specified criteria.  

However, if you take viewpoint of the query being asked, it is quite reasonable to search for flights in ANY of SEVERAL aircraft for example.  Likewise, searching for flights EXCEPT those with certain criteria is useful in (I think) all of the other groups.  So, the wording above might be misleading or confusing.   Making the conjunction of the options explicit would be more clear.

Another way to improve clarity would be to write “Find flights that have choice of the following characteristics (etc.).”  The use of the plural and “HAVE choice of …” makes it more clear that the user is specifying a query, rather than the features of a specific, single flight.

The semantics I think most users would expect is as follows:

ALL: the flight must have every one of the selected options			A AND B AND C
ANY: the flight must have at least one of the selected options		A OR B OR C
NOT: the flight may have any option except those selected			* AND NOT (A OR B OR C) = * AND (NOT A) AND (NOT B) AND (NOT C)

where * represents the un-selected options.   On writing this, I realize now that EXCEPT would be more clear than NOT.  So, above, “choice” should be one of ALL/ANY/EXCEPT.

There is at least one other possibility: * AND ((NOT A) OR (NOT B) OR (NOT C)).   This means the flight does NOT contain AT LEAST ONE of the selected options.  This is probably not very useful, and I can’t think of a good word for this form of query.  I can also imagine other types of queries, but those might better be addressed with a query language (which certainly isn’t reasonable to implement).

You wrote, "NOT can be achieved by clicking "SELECT ALL" (Aircraft, models, category/classes) … I think you meant the (Select All) checkbox … and unchecking the ones you don't want.” Aside from the semantic error here (see below), the (Select All) check box is not present for aircraft or makes/models.

By the way, where there are mutually exclusive options (aircraft, makes/models, and categories/classes), it only makes sense to select multiple options for ANY and EXCEPT, not for ALL.   You could reduce/prevent user error in these ways:
if the query specifies ALL before making any choices of options, either
Change to radio buttons, limiting the selection to one option, or 
Clear the previously clicked checkbox when a second box is selected, acting like a radio button
If the user selects options using check boxes, and then specifies ALL,
at the time the user clicks on “Finding matching flights”, issue an error message and let the user fix the query, or
immediately 
clear all the check boxes (perhaps after the user confirms/acknowledges his mistake), or
allow the user to change to ANY/EXCEPT, or revert to choice
All that said, I’d like to suggest that you do implement ALL/ANY/EXCEPT for the remaining groups of criteria.

Airports

It seems reasonable to search for flights that visited ALL of the specified airports, or all flights EXCEPT those that visited any of the specified airports.   A flight including both GPI and HCR would be ALL GPI AND HCR.   EXCEPT is pretty obvious, eliminating flights that did visit a (list of) particular airport(s). This should work with landing/departure airport queries too, I believe.

I don’t see that squishiness in airport codes is a problem, actually.  Generally, the user can eliminate the squishiness problem by explicitly listing multiple codes, even if they all refer to the same airport.  If I want to find flights that involve San Francisco, I use ANY (KSFO OR SFO).  I bet most (US)  pilots have a personal convention, and tend to use the leading K or not on all airports anyway.   On the other side of the coin, I might want to see flights EXCEPT those that involve Maui, but I might have sometimes entered OGG and other times PHOG.   So, I’d want EXCEPT (OGG OR PHOG).

One other way to mitigate squishiness would be to let the user include an optional (K) in the the airport code for example (K)SFO.  (This is not useful outside the US, I guess).  Or, allow (KSFO,SFO) in the query spec to identify the same airport.  Or support a limited set of wildcards like *SFO, which would not necessarily be precise.  Or, permit the user to specify that he’s using IATA, ICAO or FAA codes in the query string, as IATA:code, etc.

In ADD/EDIT airports, you already allow users to specify a private name for a private airport.  I assume you can search for these private names (?).   So, overall, squishiness may not be a problem.

Some additional related ideas about searching using airports are presented below.
By the way, do you ignore case when doing airport searches?

Categories/classes

Searching for flights with ALL of the specified criteria does not make sense for categories/classes, but ANY and EXCEPT do.

Your proposed equivalent of NOT doesn’t work.  Clicking “Select All” in the categories/classes group and unchecking the ones you don't want actually doesn’t have the right semantics for EXCEPT.  Such a query would find flights that match ANY of the remaining checked categories/classes, and MAY include flights that DO have one of the un-selected choices.  That is, the query would not preclude the unselected options.   What’s intended is NOT ANY of the selected choices … e.g., EXCEPT those..   Of course, a single flight can only be in one category/class, but the intent of the query would be to find flights that are in any category/class but exclude those in the specified categories/classes.

Besides, the method of clicking (Select All) and unchecking options is cumbersome, as there are groups with lots of options   If the user wants to find flights NOT in an airplane or glider or helicopter, he has to click quite a few times (if the semantics were right, of course).   I don’t see much downside to implementing EXCEPT for categories/classes.

You might as well implement ANY for categories/classes as well as EXCEPT, even though the (Select All) option makes it easy to search for ANY of the options (since they are all selected/checked).   If you implement ANY, then you don’t need the “Select All” checkbox.  Removing it would make all the groups operate the same way -> better ease of use and internal consistency.

By the way, I note with categories/classes, the (Select All) button only works once.  Other UIs I’ve experienced make this reversible, so you can easily “select none”.  There are many ways to permit this … two mutually exclusive buttons (select all, select none) is just one way.

Aircraft

I will never be one who has a large fleet of aircraft.  A member of a flying club or a CFI or ATP pilot may often fly many different specific planes with many different tail numbers.  Of course the (current) ability to query to find flights in ANY of several specific aircraft makes sense.  But it also makes sense to look for flights EXCEPT those in specified aircraft.   You are right, of course, that ALL for aircraft doesn’t make sense.  

Makes/Models

It certainly makes sense to search for flights EXCEPT those in specified makes/models.   Like aircraft, searching for flights with ALL of the specified makes doesn’t make sense.
 
Beyond that, enhancing “contains” within this group is possible, but is probably not worth doing.  It seems reasonable to search for flights in (or except in) aircraft of any of several makes (Airbus OR Boeing, or EXCEPT Airbus AND Boeing).  Reminds me of Excel filters (with which, of course, you are extremely familiar!).

You could implement regular expressions for “contains”, but that might not be something most users would want to deal with. By the way, do you ignore case when searching for aircraft?

Aircraft Characteristics

You are of course right that in any given flight, an engine can only be one type, so ALL doesn’t make sense for engine types.  However, it is reasonable to search for flights that have any of the characteristics listed EXCEPT jet engines.  ALL actually would make sense for other aircraft characteristics (e.g., flights in planes with tailwheels and a glass cockpit … perhaps not the best, but surely not the only example).   If you wanted to prevent queries with conflicting criteria (e.g., ALL engine types), you could clear those buttons when ALL was selected.

By the way, how about adding some other characteristics?  These seem useful: open cockpit, biplane, vintage, military, commercial.  Just a thought.

Nonsensical queries

You might argue that in some cases above, the user might specify a query that cannot possibly find any flights.   Let the user make that mistake and then refine the query to find the flights he wants.

Searching by and adding airports

The following (and some of the preceding?) ideas should probably be separately recorded in Github.  I can do that if you like.

When searching for an airport (Airports > Find Airport), please list the lat/long and the type of airport where applicable.

ADD/EDIT airports could allow the user to re-define a known public (what you call “built-in”) airport.  This would effectively create a private airport, just for that user, so he could search it based on attributes he is concerned about, like alternate names for such airports.  For a flight specified as visiting a public airport that has been re-defined, you’d want to record both the private and public names, in case the private name was deleted in the future. 

You could also allow use of multiple names for an airport, so the user could enter or both of KHCR and HCR,  A query for either KHCR or HCR should find flights involving that airport, regardless of what was entered in the query.   Perhaps you could permit explicitly specifying all or any of the ICAO, IATA and FAA airport codes as three separate fields?  (By the way, the Kalispell, MT airport is FAA: GPI and IATA: FCA, but IATA:GPI is Guapi Airport in Colombia.  Whew!)

To enhance finding flights by airports visited further, you could allow searching within a region, such as:
latitude/longitude: within a radius (nm) around a single point or within a rectangle defined by two points
city name: (any of the “Chicago” airports)
US states (or equivalent in other countries)
within a specified radius/distance of a city (see https://simplemaps.com/resources/free-country-cities <https://simplemaps.com/resources/free-country-cities> for lat/long of cities, from which you could calculate this)
Any of these forms could work with ALL/ANY/EXCEPT.

Since (most/all) airports have actual names, not just codes (KHCR = Russ McDonald Field) you could allow the user to enter … or automatically look up … the actual name.   It should then be searchable, and possibly included in reports.

Additionally, I see you allow the airport type to be specified (for private airports).  How about permitting searches for airport types?  It seems reasonable to search for arrivals and departures at (or using) a SEAPORT or VOR for example.
