### ISSUE TITLE
Identify runways used

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#328]
It would be handy to record which runway was used for a take-off or landing, and the information could subsequently be used in searches.

A simple UI would be to enter the runway in the route, like this: ABC:04 DEF GHI:13.  This would have the obvious meaning of using runway 04 to land not specifying the runway(s) for DEF and runway 13 to take off.  MyFlightbook would validate that the runway specified was valid, using the airport database.

For queries, the runway could be specified in the "airports visited" criterion, and when left unspecified, the query would run as it does currently.   This would also work if departure and arrival airport searches were supported as suggested in another issue, so the user could find flights that landed at a specific (short?) runway, for example.

**Comment by ericberman** [comment]
You can absolutely do this if you like in the route field, but I have no runway information whatsoever in the database, so there's no validation I can do.

**Comment by ericberman** [comment]
Note also that as a logbook - and unlike EFBs - I deliberately keep around old/closed airports.  But I have over 60,000 airports - many user defined - from around the wold and have no runway information.  Also note that KABC:34L could mean "Runway 34L at airport KABC", or it could mean "KABC to 34L" where 34L is an airport.  Any non-alphanumeric character separates airport codes.

**Comment by KayRJay** [comment]
Fair enough.  I was under the obviously wrong impression that you used some sort of public database to look up airport into (like METARs for example).   Even if you didn’t validate the information about runways, you could put the burden back on the user … if they enter a runway, it’s valid to them.

**Comment by KayRJay** [comment]
A space between one airport and another is sufficient to distinguish Runway 34L at airport KABC from KABC to 34L.   “KABC:34L” is an airport/runway, while “KABC 34L” is a flight between airports.  

As I said elsewhere, the validation and closed airports issue is beside the point.  Trust the user, but give him the functionality to specify and query against runways, valid or not.

It’s easy to, overthink things sometimes ...

**Comment by ericberman** [comment]
People use a very wide variety of separators between airports.  I could add a "Runway Names" property easily enough, analogous to the "Approach Names" property (which does capture which approach was performed to which runway at which airport - e.g., "2-ILS-RW16R@KPAE" means 2 ILS approaches to runway 16R were performed at KPAE).  But (a) even that isn't validated - it's a convention, but you can write freeform in the approach names field, and - more importantly - (b) you're technically required to record the approach names, but no such requirement exists for runways, so recording runway is already ad-hoc (and infrequent).  I'd suggest simply recording runway in the comments.  If you follow a convention like RWY#@KABC (e.g., "RWY16R@KPAE"), then you can search for it reliably.
