### ISSUE TITLE
Support entry and query on runways

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#332]
(Part of this discussion takes place in the issue about noting departure and arrival airports.   The purpose of this issue is just to separate the topics.)

It would be useful to allow the user to specify, in the route, the runway used for a take-off or landing, and to be able to search against it.   This is true even if MyFlightbook does not use an airport database to validate runway numbers against airport descriptions or look up runway  characteristics (such as length, width, surface or obstructions etc.).  A user might want to search for landings or take-offs on runways shorter than a specified length, for example (whether that characteristic is known to MyFlightbook or is simply part of the user’s own knowledge).

This feature may not be a high priority (either for users or for future implementation), but it’s worth logging as an issue for consideration.

A possible syntax that seems natural, and does not appear to introduce any ambiguities would be to follow an airport code with a colon and the runway number.   The runway number is always a two-digit number, and may be followed by a (single?) letter indicating left, right or center.   For example, ABC:04 DEF GHI:22L would mean (assuming MyFlightbook infers departure and arrival airports), “departed ABC on runway 04, visited DEF on an unspecified runway, and arrived at GHI on runway 22 left”.

Putting the airport:runway info in the route means it can be parsed and recorded in a structured way, facilitating searching and indexing, as compared with doing so in free-form text.

**Comment by ericberman** [comment]
Added "Runways Used" property.  Freeform text, but a hint that following a convention like "RWY###@xxx" makes it searchable.

**Comment by KayRJay** [comment]
Cool, thanks!   I will try it when I get back ...

Just curious though why you require the token RWY in a property that is called a runway property.   Why not use have ###@xxx?

Thanks

Ken

**Comment by ericberman** [comment]
Absolutely nothing wrong with ###@xxx; I don't require anything because I don't parse this, so I have no need to constrain it.  It's free form, no validation.  It just what I propose makes it clear, for example; otherwise 10C@27R is runway 10C at El Dorado airport (27R).  But you can do R##@xxx, ###@xxxx, ###!xxx, whatever convention you like.

**Comment by KayRJay** [comment]
got it.  As long as I can query for departure on a given runway at a specific airport, I’m good.

thanks;
