### ISSUE TITLE
FAQ Links/Branding on prod site link to staging

### ISSUE THREAD

**Issue by btusi** [ericberman/MyFlightbookWeb#339]
At least some of the links/branding/etc. on https://myflightbook.com/logbook/Public/FAQ.aspx point to MFBStaging. For example, the last question on the page is currently, "Will the FAA accept signatures on MFBStaging?"

**Comment by ericberman** [comment]
Huh, I'm not seeing this - either with myflightbook.com or www.myflightbook.com.  Also doing a force refresh, still not seeing a problem.  

What browser/device are you using?

**Comment by btusi** [comment]
Strange, I'm not seeing it anymore either. MacOS Mojave with latest Firefox. The URL should be correct; I copied/pasted it.

Apologies for the false alarm. I'll take screenshots if I see it again.
