### ISSUE TITLE
User preferences for ENTER/RETURN

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#380]
Related to, but different from, issue #311 (Warn when navigating away from partially filled flight), it would be helpful to have a user profile preference to control what happens when the ENTER / RETURN key is pressed.    It can (as it does now) issue a "commit" (e.g, adding a flight as if the ADD flight button were pressed).   Some users might prefer that ENTER navigates from field to field, as TAB does.  Or other treatments ...

It is easy to accidentally hit ENTER, and add a flight when the user is not quite done filling in fields.   Users might have different preferences for the way ENTER is handled.     These options might be useful:

When ENTER/RETURN is pressed

- Commit the changes (e.g., add the flight)
- Navigate to the next field (like TAB does now)
- Do nothing
- Issue error ("Press ADD Flight to record the flight") 

I can understand the argument that four options may  be overkill.   Since there would be a visual cue if ENTER / RETURN worked like TAB, it is sufficient to implement only the first two options.

**Comment by ericberman** [comment]
Are there any websites that use enter to move to the next field?  Enter (when not in a multi-line textbox, where obviously a new line makes sense) to submit a form is pretty ubiquitous on the web, I'm not sure that there's any need for this.

Plus, the ASP.NET architecture I'm using has the notion of a "Default button" (i.e., what gets pressed when you click Enter) all over the place, so this would change a ton of code in a ton of places; absent  compelling data to suggest that this is something a lot of people expect/want/use elsewhere, I'm not inclined to do this.

**Comment by KayRJay** [comment]
It may not be common for websites to disable using ENTER to submit a form, but it's certainly not unknown.   There are many posts discussing disabling "implicit form submission".    Some discussions are somewhat dated, but there are recent ones too.  Some website developers want to be able to do this for whatever reason on their pages. 

[This one](http://www.alanflavell.org.uk//www/formquestion.html) might be a good read.   Another [author](https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/)  believes it is better to support implicit submission, but also says "Despite being vital for assistive technologies and an important user convenience, **many** web forms prevent it for one reason or another. "  (Emphasis added.)


Quicken (on Windows) supports the user choice as an option:

<img width="302" alt="Screen Shot 2019-10-04 at 4 40 41 PM" src="https://user-images.githubusercontent.com/16978320/66244460-c932b480-e6c5-11e9-899d-11bb65f47fd8.png">

Particularly with a long form, with lots of data entry fields, it seems quite likely a user may prematurely submit a form.  I know it's happened to me several times on MyFlightBook.

I don't know how to make a **compelling** case that a lot of people would expect/want/use this feature.   I haven't undertaken an exhausting search of websites and applications on this topic, but a Google search definitely shows the topic does come up from time to time.  (I have a number of saved URLs, but I thought I'd not copy them here.) 

To me, this seems a useful user preference .  This feature would be most useful on Add new flight page (the only one with many, many enterable fields).   That would limit the code you'd need to touch.  (However, it might be best to support this for every page with a data entry field.)  It would remain rather obscure, just on the Profile page, so wouldn't automatically affect anyone.

**Comment by ericberman** [comment]
If I did it, I'd absolutely make it an explicit preference. Even the links you cite say it's better to support implicit submission.  I don't know how to quantify his "many" - if you think it's a bad idea, then even 1% of sites would be too "many".  

But I'm strongly, strongly disinclined to do this.  The sites that do so are overriding built-in default HTML/browser behavior (which I am generally loath to do and makes it fragile); however many "many" is, it's still a distinct minority of sites; the framework has built-in support for implicit submissionbaked in all of the place that I would have to override (meaning I'd be touching a crazy amount of code in order to fight both the browser and the framework...); and finally, the "cost" of an incorrect implicit submission is low (just edit the flight).

**Comment by KayRJay** [comment]
Understand your concerns.   Not a big deal.
