### ISSUE TITLE
Select multiple flights in logbook

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#382]
In some cases, it would be helpful to operate on multiple selected flights at once, as follows:

- Delete several displayed flights, perhaps after a query or importing a number of flights
- Share (on Facebook), email, or tweet several flights
- Request signatures for several flights

Of these, the most useful of these is deleting multiple flights.  It is (presumably) the easiest to implement.   It would be quite helpful to users even if deleting flights was the only option available.

The user interface wouldn't require much change or space.   A simple checkbox ☐ placed to the left of the flight date would indicate selected flights.  (Of course the selection is reversible by re-checking the box.)   At the bottom (or top) of the page, there could be a button for "Delete selected flights" (as well as others for the other options, if implemented).   A nice touch would be to grey-out the button if no flights are selected.

This option would only apply on a page-by-page basis, so there would be no flights selected when navigating from one page to another in the list of displayed flights.

However, it would be convenient to select many (or even all) flights shown all at once, for example after a query.   Thus, adding a "Select All" (and "Select None") option would enhance this functionality.

**Comment by ericberman** [comment]
Just an FYI - Request Signatures already supports multi-flight if you do it from Training->Request signatures.

**Comment by ericberman** [comment]
Oh - FB/Twitter don't handle multiple URLs all that well; they really like one link/post.  Email is probably a more realistic scenario.

**Comment by ericberman** [comment]
Look in the overall drop menu (i.e., next to the number of flights) to turn on select mode; that's also where you can see any operations to perform on selected items.  See my commit notes for more reasons why it operates the way it does.

Note that selection *does* persist if you go to another page, but the "select all" box only checks/unchecks the visible page's boxes.

**Comment by KayRJay** [comment]
Works great!    Clever way to save space, replacing the down arrow with a checkbox.   I’d argue that the box should be on the left.  See issue #400.  The new UI for ☐ and V works equally well on the left.   Summary reply to your last comment on that issue.
Either the ☐ or  V should be on the left to make it close to the flight being selected.
A flight is identified by its date … on the left … so the  ☐ or  V should be near that id.
Not all hamburger menus are on the right … see Youtube, Gmail.   Personal preference.
Hamburger menus are not analogous to the drop-down menu; one hamburger menu per page, not corresponding to any specific item
But in any case, thanks for the new feature!

Ken
