### ISSUE TITLE
Offer QR code to currency or totals RSS in html format?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#386]
would link to https://myflightbook.com/logbook/Public/RSSCurrency.aspx?uid=...&HTML=1 and https://myflightbook.com/logbook/Public/RSSCurrency.aspx?uid=...&HTML=1&totals=1

**Comment by ericberman** [comment]
https://www.nuget.org/packages/QRCoder/

**Comment by KayRJay** [comment]
For some reason, the links to public MyFlightBook entries above open the Apple News app on my Mac, where, obviously, the page is not found.   On my iPad, iOS gives an error. I tried it in Safari and Chrome (on Mojave).   The link to nugent.org works fine.

If I remove the ?uid ... parameter, and stop at .aspx, I get the following message in Chrome (but not Safari).

<img width="828" alt="Screen Shot 2019-10-04 at 10 48 37 AM" src="https://user-images.githubusercontent.com/16978320/66224977-899fa480-e694-11e9-8d50-077356624f63.png">

**Comment by ericberman** [comment]
Yes.  Note the ellipsis in the URL - that's where a parameter goes that grants access to one's data.  I didn't want to expose that here in Github.  If you go to the home page and copy the link for the RSS feed (from the footer(), you can get your personal URL for your account; append "&HTML=1" to that to read it (currency) or "&HTML=1&t=1" to read it (totals).  (Without the "HTML=1" parameter you'll just get XML)

**Comment by KayRJay** [comment]
That works.   Thanks for clarifying for the millions of others who will access this issue in Github! 😀

**Comment by ericberman** [comment]
Actually I think the QRCode is a red herring here.  No need for it.  Just have a sharelink.
