### ISSUE TITLE
Record flight departure and arrival times at each airport

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#408]
Currently, we can record the flight departure and arrival times under Times and Telemetry.   However, for flights that visit multiple airports, the times recorded are only the initial departure time and final arrival time.    There is no way to record the departure and arrival times per flight segment (departure from one airport and arrival at another).

When a long trip is taken, with visits to multiple airports, it might be helpful to record the departure and arrival times per segment.   This could allow correlation with historical weather data or other conditions specific to a flight segment.   A business trip from SFO to NYC is one trip (aka "flight"), but might involve staying overnight somewhere.   For some cases, a user might want to record that multi-segment "flight" as if it were a "trip" with some long layovers.

The time spent at an airport (for a $100 hamburger or refueling) is the difference between a segment's arrival time and the departure time of the next segment.

The image below shows how you might permit recording departure and arrival times per flight segment.   Without the checkbox, the current behavior would be specified (initial departure time to final arrival time).   Note that all times should probably be optional.  (Certainly the arrival at the initial airport is probably associated with an entirely different "flight", as is the departure time from the final airport.
<img width="907" alt="Screen Shot 2019-11-05 at 2 18 37 PM" src="https://user-images.githubusercontent.com/16978320/68521153-6b146680-025b-11ea-9eaa-5022c847a72c.png">
Note that the just-added ability to record the start and end Flight Meter time also applies to an entire flight.   Ideally, it would be possible to record the Flight Meter start and end time per segment.

**Comment by ericberman** [comment]
You can achieve this by breaking up multiple flights into multiple entries, or consolidating them into a single entry.

**Comment by KayRJay** [comment]
Of course.  That is rather obvious.   But, when the segments are separate "flights" there is no way to tie them together into one "trip" with multiple segments.

**Comment by ericberman** [comment]
Indeed.  I have the notion of a "flight" without the concept of sub-segments..  If I were to do that, I'd probably make each flight a segment - i.e., have a way of grouping entries into a single flight.  Not sure what problem I'm solving, though.  The main issue is for various ratings requirements that require things like a cross-country flight of at least X miles that lands at at least N airports.  By definition, though, those need to be grouped to constitute a "flight".  the real request here, IMO, is to break down the intermediate engine/flight/hobbs times as you go from A->B->C in a single flight. True, but I've never had anybody suggest that they need to know what the intermediate hobbs/flight/engine times were.

**Comment by KayRJay** [comment]
Yes, grouping “flights” into a “trip” would address my suggestion.   This idea occurred to me as a straightforward extension of the existing data model, where a flight can involve multiple airports, adding the ability to “decorate” airports with departure and/or arrival times.  Clearly a entirely different UI and significant data model changes would be needed to somehow link multiple flights where each flight is a “segment”.

Of course, I am not all that experienced as a pilot.   I am never going to be ATP rated, and perhaps commercial pilots are not your target.    It just seems there are reasons to log times and places other than for a rating certification.  I’m thinking some pilots would want to record “missions” that involve multiple flights.   

It’s not so much Hobbs or engine times I was thinking of, but times of day.    This would serve something like a delivery route, with multiple pickups and drop-offs during a day or a few days.  Or, a salesman visiting multiple locations on a business trip.  Or, a flying vacation with the family.

Certainly this is not a critical or high priority requirement.  I’m just thinking out of the box here, noting that a pilot may want to log flights for reasons unrelated to achieving a rating.   This feature is an example of something an electronic logbook can do that a paper logbook cannot (easily) do.   Although this may be the first time someone has suggested this idea, there are could be other users who would find such a feature useful.  Not every user who has an idea takes the time to suggest it.

**Comment by ericberman** [comment]
Quite true, but to precisely your point, that's why this is typically done as multiple entries and why a grouping mechanism of multiple flights makes more sense than making a flight itself more complex/hierarchical.  After all, in addition to wanting to know your engine/hobbs/flight for each segment, you might want to record IMC, night, PIC, carrier landings, etc. per segment - i.e., everything that can go into a flight.

My point about ratings was that - lacking an explicit grouping mechanism today - putting all of this in a single flight is the only way to indicate that you've done the required flight.  (By the way, not just ATP - this applies to Commercial, Instrument, and even Private Pilot.)  So in general, you have complete discretion to either coalesce a "trip" into a single flight entry, or to break it out into multiple entries, depending on how granular you want to get per segment; the long cross-country requirements for these ratings are the only exception where you can't break it out like that.
