### ISSUE TITLE
Error and warning messages should provide more context

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#417]
The message "Are you sure you want to delete this flight?  This action cannot be undone!" would be more useful if it identified the flight about to be deleted.

The words "This flight" is somewhat vague.  Although the user presses "Delete this flight" from a pop-up menu, when the cursor is located on a particular flight, it is a bit easy to be confused about which flight is about to be deleted.   This is especially true because the pop-up menu is far to the right of the flight's date.

Especially since the operation can't be undone, it would be wise to include the date (and perhaps the route) in the warning message.  It should include the date of the flight, and perhaps the route, as follows:

"Are you sure you want to delete the flight on dd/mm/yy, route xxx xxx xxx.  This action cannot be undone!"

The principle of including more information in warning and error messages should be followed throughout.

**Comment by ericberman** [comment]
Agreed.
