### ISSUE TITLE
AR-95-1 new hoist currency

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#430]
1 hoist operation every 90 days to maintain currency.

**Comment by dkroll89** [comment]
![B8B27A97-D47E-47E4-8624-02F240116328](https://user-images.githubusercontent.com/59098272/71284817-41a22c80-2329-11ea-978b-a38a8b19b714.png)
![1890BF1D-0608-4167-880F-65DB1B7CD9B7](https://user-images.githubusercontent.com/59098272/71284819-41a22c80-2329-11ea-9be4-d992b67de7d6.png)

Eric,

The document is CAC access only. I have included screenshots of the cover and applicable section for currency. Let me know if you need anything else.

**Comment by ericberman** [comment]
I'm going to suggest using the existing custom-currency rules on this.  Especially not having the full rules (e.g., does this only apply to H-60?), that will let you do them in a way that is right for your situation.  I think it's got everything you need.
