### ISSUE TITLE
Add airport as locator to the Day/Night (sun angle/sunset/sunrise) feature

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#443]
The current Day/Night feature is quite nice and useful.  Knowing when the sun sets at a given location surely is important when planning a flight.

As an alternative to clicking on the map, or entering the (usually not known) latitude and longitude as a locator for this feature, it would be handy to be able to enter an airport code or zip code.   

There are free databases available with this information:

- [Airport to lat/long](https://www.partow.net/miscellaneous/airportdatabase/)
- [Zip code to lat/long](https://public.opendatasoft.com/explore/dataset/us-zip-code-latitude-and-longitude/table/)

**Comment by ericberman** [comment]
Haha!  See, this is why I didn't expose the playpen in the footer! ;-)

Note that you can zoom/pan the map and then click on it to fill in the lat/lon.

**Comment by KayRJay** [comment]
Would result in too many feature requests?

I did mention clicking on the map.

I’m currently adding another feature request/issue re lat/long and zip code for other features.   Sorry about that! 😀

**Comment by ericberman** [comment]
Note that I have an airport database, so that's easy.  As a debugging tool, the work of adding zip code support does not make sense (and besides - zip codes can cover large areas; by definition, this only works at point locations - i.e., a single latitude/longitude/time tuple.

**Comment by KayRJay** [comment]
I see you've closed the issue, but will you add the "easy" feature of specifying the location for the Day/Night feature by airport code?

I don't get the reference to a debugging tool.  I think zip codes can be useful in several places, so see the new issue (once I submit it).

**Comment by ericberman** [comment]
You didn't look at the commit did you. :)

**Comment by KayRJay** [comment]
No … just read the issue. I was typing my comment after your comment but before your commit!   Real-time dialogue going on here.  ;-)

**Comment by ericberman** [comment]
Oh, the reference to debugging: the only reason I built this tool was so that I could validate my autodetection code.  E.g., if I look at a GPX file or KML file with telemetry (= time-stamped series of latitude/longitude points), I can detect night flight and night landings from that.  This would let me see if my autodetection code was about right.

**Comment by KayRJay** [comment]
Ah, so if you come to believe zip codes (and wider use of lat/long) can be useful for users, then it might make the possible feature list.  I'll try to be be persuasive in my issue on this topic!

**Comment by ericberman** [comment]
You're going to need to be persuasive on zip codes, for a few reasons:
 * It's US-only
 * It requires a new data source or service, and
 * (Most importantly) I'd understand out how zip codes relate to pilot logbook functionality.

**Comment by KayRJay** [comment]
There are postal codes in most countries.   [Here](http://www.geonames.org/about.html) is a free service whereyou can get lat/long from postal codes (or vice versa), in many locations world-wide.  There are downloadable [files](https://download.geonames.org/export/dump/) containing a lot of information including postal codes, place names, elevation, lat/long, country codes, time zones, etc.

I'll explain my rationale for using zip/postal codes in the other issue.

**Comment by KayRJay** [comment]
Thanks for implementing this feature.

I tried the airport code, and the map doesn't get re-drawn until I "Get times".  Seems it should redraw on Enter or Search.
