### ISSUE TITLE
Provide more unique information about airports

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#448]
MyFlightBook could provide info on use of airports by pilots who’ve logged flights. This is info that is unique to MyFlightBook because it is based on actual flights, and quite different from something like the AOPA airport database.

When you display info about a particular airport, you could include ...

- The most recent shared/public N flights visiting the airport, and

For a range of dates, 

- A list of shared/public flights visiting the airport
- The number of pilots visiting the airport
- The number of flights visiting the airport
- a list of aircraft types that have visited the airport
- a list of visiting specific aircraft tail numbers from shared/public flights
- a list of pilots who have published flights visiting the airport

And, if you ever add airport info to a pilot's profile, you could also report the number of pilots with airplanes hangared there, and the number of pilots who consider an airport a "home" airport.

This would be a nice feature in a social networking sense as it relates to sharing and finding people.

**Comment by ericberman** [comment]
I like the idea, but at the moment, this is insanely expensive (performance-wise) to do.  Your a MySQL guy - perhaps you can provide some database insights here?

The underlying issue is largely twofold:
 * The airports in a given flight are in a varchar string.  I.e., I can't do a join here.  You can record airports how you like in the Route field - it's unstructured.  A sample might be "KSFO-PAE @YKM @45.34N122.34W NOTINDB".  Note some things here: (a) can be KSFO or SFO (same airport), (b) any non-alphanumeric (or "@") character separates them, (c) "@" prefix next to a code means to bias towards a navaid rather than an airport (which may or may not exist - in this example, @YKM means the Yakima VOR, but it would mean Yakima airport if the VOR didn't exist), (d) you can make up ad-hoc lat/lon fixes, and (e) it's fine if you have a code like NOTINDB that's not in the database.  Anyhow, the point being that it's not something you can do a join on. 
 * North of 8M flights - and growing - that (for obvious reasons above) are not indexed on airport.

Whenever I do these sorts of queries for a distinct user, I do two queries: first I do a query on the user's flights (solving the 8M flight problem) and build up the list of the user's routes.  I then do some string munging on that list to get a normative list of airport codes, and then I can do a 2nd query which can then go into a database query against the airport list.

But that all breaks down if I have to go through 8M+ flights. 

The suggestion here does simplify things a bit from the other angle, since you're coming at it from an airport itself.  So in this case, you'd start with the airport code, find its synonyms (e.g., Maui is OGG or PHOG, San Francisco is KSFO or SFO, other airports have obsolete codes), typically resulting in 3-5 codes, and then search across 8M+ records for flights that have hit them.

But even that's a crazy slow query.  Is it just a matter of indexing on the route?

**Comment by KayRJay** [comment]
Thanks for the reply.

> The airports in a given flight are in a varchar string ...  the point being that it's not something you can do a join on.


Yeah, unstructured info is a challenge, often.  XML databases (and capabilities like XML types in Oracle, Postgres and SQL Server) could help, but that’s not what we’re dealing with.

> North of 8M flights - and growing - that (for obvious reasons above) are not indexed on airport.

A sensible decision.

> The suggestion here does simplify things a bit from the other angle, since you're coming at it from an airport itself.    ... [it becomes a] search across 8M+ records for flights that have hit [the airports].
But even that's a crazy slow query. Is it just a matter of indexing on the route?

I think so.  However, text searching isn’t the quickest thing either with 8M++ rows.

Another idea that might help is to store, for each flight, a normalized list of airports, in separate columns, extracting the relevant info from the route.   It’s probably the case that most routes don’t include more than a handful of airports.  (I think you might be able to tell that now, with some clever queries that summarize the achievement of "Most airports in a single flight’ across all users.) 

So, if the max was, say 5 airports, you would have 5 additional columns, AIRPORTn (1-5), each with a single code. (You wouldn’t really need to include anything for synonyms, if you had a preferred code for each airport).   Index those columns.  This shouldn't require a lot of extra storage or large indexes, as the airport codes are short strings.

Then the queries become simple.  And if you don’t capture all airports for a given crazy flight, who cares?  In this case, an approximate value is surely good enough.  No one but you or I would ever know!  😀

If you (or MySQL) optimize properly, you’d be finding flights out of the 8M++ based on a range of dates first, then subsetting down to those flights where any of the AIRPORTn columns is the ONE airport in which you’re interested.  Especially if the date ranges are narrow, this should be very quick!   

On the other hand, the number of flights visiting a given airport in all of MyFlightBook history is likely relatively manageable.   So, this query could be fast either way it is optimized (though OR predicates aren't always optimized efficiently).

   SELECT stuff FROM flights WHERE
     flightdate BETWEEN firstdate AND lastdate 
     AND (airport1 = “airportcode” OR airport2 = “airportcode” …)

You’d might want to look at [MySQL hints](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-overview) to force the optimizer to choose properly.

**Comment by ericberman** [comment]
good stuff to think about - I think the date restriction might be the biggest optimization of all here.  Looking back through all time = 8M flights.  Looking back a week or a year is a moving window.

**Comment by KayRJay** [comment]
Another thing you can do is convert the ORs to UNIONS, where you gather the flights for the given airport in each of the 5 separate airport columns in separate queries and combine the results via UNIONs:

SELECT stuff FROM flights WHERE
flightdate BETWEEN firstdate AND lastdate
AND (**airport1** = “airportcode”)
UNION
SELECT stuff FROM flights WHERE
flightdate BETWEEN firstdate AND lastdate
AND (**airport2** = “airportcode”)
UNION 
...

But yes, a narrow date range is likely the best hope!

**Comment by KayRJay** [comment]
The number of flights visiting a given airport (over all time) is likely quite small compared to the 8M++ flights, even over a range as large as a year. So, it actually might turn out that finding airports first (possibly using UNIONs), then narrowing by date range, would be the best way.   

I’ll be interested in your findings as you explore different alternatives.

**Comment by ericberman** [comment]
So now that #553 is taking a look at a rolling window of flights, I've got a boundary on the computation involved here and suddenly this gets a lot more interesting.  Couple this with the fact that I now have country/region data for airports (see issue #699) and it gets yet a bit more interesting.  I'm enumerating the flights over the last 7 days and building up the set of airports from that, from which I can then compute:

 * Longest route flown (total distance - though this can be very noisy)
 * Furthest distance flown (from departure - though this can be very noisy)
 * # of flights that referenced the airport
 * # of distinct users represented by those flights
 * # of distinct aircraft (tail numbers) represented by those flights - with the caveat that anonymous aircraft are treated as one aircraft but often represent multiple physical airframes.  I do *NOT* list the specific tail numbers for privacy reasons.  If you want to use Flightaware for this, be my guest.
 * # of distinct models represented by those aircraft.

Just in simple debugging, I'm seeing in the last 7 days between 3,000 and 4,000 airports visited, out of something like 50,000 in the system.  So most airports do not have any visit data, which means I'm reluctant to make it a standard part of the data throughout the places where I show airport information.

Similarly, the % of flights that are public/shared is pretty small, so many of the top airports will not have associated public flights.  In displaying public flights, I actually go back 30 days.  At the moment, 30 days represents 60,505 flights, of which 909 were flagged as public, so about 1.5%.  

For that reason, I'm showing just the top 20 or so airports with their stats, and clicking simply shows you the airport on a map.

I'm going to close this issue out as being finished...at least to the degree that makes sense now; I think what I've done gets most of the juice from this orange.  If there are additional data points or enhancements that are interesting and doable, let's open new issues to track those.

**Comment by KayRJay** [comment]
Thank you so much, Eric.   I'm very glad that you've been able to return to this topic.  

I do see the extra info on Airports > Airports visited, and one more line of info on the Home and About MyFlightBook pages.   I must be missing something, as I don't see any other additional info, so please give me a pointer.

And, Happy Chanukah!

**Comment by ericberman** [comment]
Always gotta watch out for me closing bugs before I update the website; the lag time can sometimes be a few days (updating is slow and interrupts the website for a few minutes). :)

Anyhow, it's live as of about 5 minutes ago.  Click on "About MyFlightbook" to see the airport information and popular model information.

**Comment by KayRJay** [comment]
Awesome!    Thank you!

**Comment by ericberman** [comment]
Oh, and Happy Chanukah to you as well!

**Comment by KayRJay** [comment]
It's really great the way it is, but I wonder if it wouldn't be slightly more useful if it were in a tabular format, without all the repeating text?   Being a relational database guy, I aways prefer structured data.   It's also easier for a human to read, I think.   More like this:

![image](https://user-images.githubusercontent.com/16978320/102286910-7faf3d80-3ef6-11eb-889c-15c8d224dd96.png)

**Comment by ericberman** [comment]
Trivial to implement that, but significantly more real estate. ..

**Comment by KayRJay** [comment]
Wider, but not as long vertically.  And fewer pixels.   Easier to read.   Can be downloaded and sorted (e.g., by most different pilots).  Or, you could implement column-header based sorting.   Many advantages to a structured format.   Especially if it is trivial!

**Comment by KayRJay** [comment]
Or you could leave out redundant info like DENVER ... DENVER.  (Not sure why the format of the  airport names differs so much one to another ...).

**Comment by ericberman** [comment]
The name of the airport comes from a bunch of sources, and is a blob of text.  Sometimes it's ALL UPPER CASE, sometimes not, sometimes it's just the name of the field ("Logan Airport"), sometimes it's the name of the town it serves, sometimes (as in the case of Denver), it's the name of the airport and the city it serves.  The "Denver" is redundant because it is in both the name and in the location, but sometimes the name doesn't include the location.

**Comment by KayRJay** [comment]
Funny, so many other things are standardized!

**Comment by ericberman** [comment]
Yeah, if I were to pay a bunch of money for Jeppesen data I could probably get cleaner data, but I'm cheap about that.  And the FAA - which provides its data for free - follows the conventions you're seeing for Denver.  

As for the table, my main hesitation is just that it pushes the top models down the page; I kinda like seeing them side-by-side.

**Comment by KayRJay** [comment]
No reason to pay for that info.  Too bad the free services don’t do anything similar though.  I suppose it all comes down to time, money and (lack of) demand.

Re the format .. fair enough, but you could have two tabs: AIRPORTs and MODELS, so each page would show only one set of data.    There’s really no relationship between "Most visited airports” and “Most flown models”, so the side-by-side display doesn’t really provide any additional info.

To be clear, I’m not really strongly arguing the case.   Just exploring ideas.
