### ISSUE TITLE
Three enhancements to analysis tab

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#482]
(a) should be able to add numeric/summable properties to the analysis tab
(b) should be able to display more than one at a time.  Even if graph can only show one at a time, at least the underlying table can show more.
(c) Need a download-to-excel link

**Comment by KayRJay** [comment]
Those three enhancements would be useful, and should probably be done even if the logbook view for subtotals (issue #481) is implemented.   The logbook approach offers other features beyond the Analysis feature, even with these additions, including grouping by criteria other than time periods.

**Comment by ericberman** [comment]
The main "other" grouping besides time periods is by model or by aircraft, and I do these both today (just not here).  Totals can already be grouped by model (Profile->Preferences) and aircraft (download your aircraft and it shows your totals per aircraft as well).

I was planning to add these to the analysis tab with this issue.

**Comment by KayRJay** [comment]
Makes sense to add these two grouping criteria to Analysis, as Profile>Preferences>Totals and then doing a separate query to see the result is cumbersome (turning on and off, etc.).

I'm posting additional comments in issue #481, so stay tuned.

**Comment by ericberman** [comment]
Note that "Running totals" also goes away for anything that isn't time based.  E.g., running totals has no meaning if you group by aircraft.

**Comment by KayRJay** [comment]
To be precise, running totals only make sense when the underlying data is sorted in ascending order by date.  Usually that also means the data are grouped by a time period (such as a date range).

There is one exception ... group by N flights.  (Not that again!).  Grouping by N flights actually 
does means a set of consecutive flights in a chronological order.   So, it's sort of a time period, but not precisely matching a date range.

**Comment by ericberman** [comment]
As far as I can tell, grouping by "N" flights falls into the category of "this is something that is possible to do", not "this is something has any actual value."

**Comment by KayRJay** [comment]
More comments later ...

**Comment by KayRJay** [comment]
Another enhancement for Analysis ... add Grand Totals at the bottom of the table of sub-totals.

**Comment by ericberman** [comment]
That's actually redundant on two levels: (a) if you have a running total, then by definition the final running total is your grand total, and (b) just click "Totals" and you see your grand totals.

**Comment by KayRJay** [comment]
My bad.  I should have thought more than 5 seconds about this.   

If you do add multiple metrics to the table, will you have running totals for all of the metrics?

**Comment by ericberman** [comment]
Yep!  Interesting challenge that brings up: can have a very wide table.
