### ISSUE TITLE
Minor bug on drop-down for templates

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#486]
The drop-down menu for edit/create/copy a template doesn't display properly (tested on Safari and Chrome):

<img width="250" alt="Screen Shot 2020-02-06 at 10 36 21 AM" src="https://user-images.githubusercontent.com/16978320/73963268-31d8aa80-48cd-11ea-98ba-14347722b811.png">

**Comment by KayRJay** [comment]
Additionally, when copying a template in my profile, the name of the profile does not have the word "Copy" or "Copy n" appended to it.  Thus, I can have several identically named templates (until and unless I rename them).  As proposed above, the template should automatically be renamed as the macOS Finder does when duplicating a file.

Also, when you delete a template, the confirmation message should include the template name in the confirmation message:

"Are you sure you want to delete this template?  
    Template name
This cannot be undone."

**Comment by ericberman** [comment]
I can't reproduce the lack of the "copy" suffix.  When I choose copy, it creates a new copy with the word "copy" and puts it into the edit part.  Note that I do limit the length of the name to 45 characters, so the "Copy" at the end can get truncated.  (I limit to prevent things from getting too wide in the drop-down).

**Comment by KayRJay** [comment]
Here's what I have in my profile

<img width="1418" alt="Screen Shot 2020-02-06 at 11 00 38 AM" src="https://user-images.githubusercontent.com/16978320/73964710-fa1f3200-48cf-11ea-961a-fbe049898aaa.png">

Maybe instead of truncating at the end, collapse the middle with ellipses ...

AA Checkride: Basic Commercial Maneuvers _Basic set of maneuvers ... Copy n

**Comment by ericberman** [comment]
Yep, that's the long one, it's just getting truncated at 45 characters.  I don't have a good algorithm ellipsifying the middle; it's overkill for this, I think.  You get your copy, you can edit it as you like.

**Comment by KayRJay** [comment]
Sure, it's possible for the user to edit it, once he figures out which one he wants to edit.  But it's not hard to disambiguate.  

Since you're already creating the disambiguation text, this simple algorithm for splitting in the middle is hardly overkill (one new line of code?):

```
Tag = "Copy" or "Copy n" or "Copy nn";   /* as needed; > 99 copies is unlikely*/
If "Copy" SplitPoint = 4 else if "Copy n" SplitPoint = 6 else SplitPoint = 7 ";  
NewTemplateName =
    LEFT(OriginalTemplateName, LENGTH(OriginalTemplateName)-SplitPoint) && " .. " && Tag;
```

**Comment by ericberman** [comment]
When you copy, you are IMMEDIATELY in an edit mode where you can edit it as you like.

**Comment by KayRJay** [comment]
True, but if I don't happen to edit it right then, then I do have multiple templates with the same name.  

I'm just trying to be kind to the user.

**Comment by KayRJay** [comment]
Also, this is what I get when I make a copy of a copy:

FAA Checkride: Basic Commercial Maneuvers -  - Copy

I don't get "Copy 2".

**Comment by ericberman** [comment]
Yes, a copy of a copy will be copy copy (truncated to 45).  I'm fine with that.

**Comment by KayRJay** [comment]
"Copy copy copy"  is longer than “Copy 3”.  But I can understand you don’t want to count the copies.

I still think middle ellipses is better than truncation which can happen before the word “Copy”.

**Comment by KayRJay** [comment]
There's still something awry.   I had several copies of 

FAA Checkride: Basic Commercial Maneuvers - - Copy

I deleted them all, one by one.  Now I have several copies of

FAA Checkride: Basic Commercial Maneuvers

These templates don't seem to be getting deleted.   And none ever said "... Copy Copy".  Only one "Copy".

**Comment by ericberman** [comment]
Just tried deleting them one-by-one in your account, worked great.

And i tried recopying and re-deleting.  Worked great.  You won't get "copy copy" for these because it's too long and I'm using your algorithm for ellipsis.  So the first time you copy it you get "...Copy".  The next time you copy it, I have to trim back the "...Copy" and put in the ellipsis before I add the "Copy", resulting in only one "Copy."

As far as I can tell, everything is working here as expected

**Comment by KayRJay** [comment]
Why do you trim off the ‘ Copy‘ before adding it back?   And also, why is the first addition “ - Copy” instead of just “ Copy”.   There’s no need for the leading “ -“.

Shouldn’t it be

FAA Checkride: Basic Commercial Maneuvers
FAA Checkride: Basic Commercial Man... - Copy
FAA Checkride: Basic Commercia... - Copy Copy
FAA Checkride: Basic Comm... - Copy Copy Copy
FAA Checkride: Basic ... - Copy Copy Copy Copy

The initial part of the name (before the ellipses) is truncated more and more each time, so it is shorter than the one before, by 5 letters (“ Copy”).  But that’s not ideal, as eventually the name is completely lost.

If you used “Copy n” for each copy, the initial portion of the template name wouldn’t get shorter and shorter each time.  You’d use the first up to 37 (= 45 - 8) characters of the name and add the suffix.   Does this pseudo code work?

If the name contains “Copy n” then 
        replace with “Copy n+1”;
else
          shorten the name if needed to 37 (= 45 - 8) characters and append “… Copy 1”;
end if;

This would result in the following:

FAA Checkride: Basic Commercial Maneuvers
FAA Checkride: Basic Commercial M...Copy 1
FAA Checkride: Basic Commercial M...Copy 2
FAA Checkride: Basic Commercial M...Copy 3

Only the last character would change with each copy, and the overall length would stay the same.  9 copies would be plenty.

**Comment by ericberman** [comment]
And indeed you see that the ellipsis algorithm is not as simple as you proposed.  I'm doing exactly your proposal - trim back to 37/38 characters, add an ellipsis, then add "Copy".  Doesn't require re-enumerating your list of templates to see which ones contain "copy"; doesn't require scanning to see if you end with "copy x".  

Note that your revised algorithm can still lead to multiple with the same name.  E.g., even if you have FAA Checkride: Basic Commercial Maneuvers", the first copy will be "FAA Checkride: Basic Commercial M...Copy 1", and the 2nd copy of that original item will yield the SAME name.  You have to hit the database, find the other templates, see if Copy 1 exists then move on to Copy 2.

The current behavior is more than adequate; I don't see benefit in further optimizing.

**Comment by KayRJay** [comment]
I proposed two algorithms, and  both actually potentially lead to duplicates. You’re right, of course, that duplicates are possible unless you know the number of templates with the same “base name”.   Determining that number isn’t worth it.  Hadn’t thought through how to completely eliminate the possibility of duplicates.
 
Either of my proposals, though, seem quite simple and easy to implement.   All that's involved is how the new name is constructed.   I prefer either approach to the current implementation.   

With the “Copy Copy Copy" approach, the initial string is truncated more and more each time a copy is made.  Duplicate names will not occur until a copy of a copy is done 9 times ("Copy " times 9 = 45).  

The "Copy n" approach does require scanning the string for the text “Copy”, but the string is already at hand, and no database hit is required.  A duplicate can occur if the user copies "Copy 2" and there is already a "Copy 3" for example.   His bad.

The likely scenario is that users will rename a template when they copy and modify it, and remove the word “Copy” from the new name.

So, both my proposals require only a small change in the way a name is constructed.  The current implementation always adds *one* "Copy" keeping the name within 45 characters.   Both of my proposals still limit the name to 45 characters.  The benefit of either of my approaches is that no duplicate names occur (except in odd cases of copying copies).

One last point: eliminating potential duplicates is the reason you rejected the "Copy n" approach.  However, the current approach will *always* create a duplicate name when a copy of a copy is made. The two other approaches only have the *potential* of doing so.  So, my favorite approach still is "Copy n", which has the added advantage of not shortening the important part of the name.

Whether it’s worth it to you to make the (small!) effort to make this change is of course up to you!

**Comment by ericberman** [comment]
Not true.  The current implementation adds multiple "Copy", it just *sometimes* can trim that back.

E.g., if your template is called "Template", then copy it gives "Template Copy", and copy that gives Template Copy Copy".  Copy that and you get "Template Copy Copy Copy".

The reason you're only seeing one "Copy" is because you're doing this with a long name.  By definition, something somewhere has to give.  So I don't see value in spending my time over optimizing about what gives.  Plus, it's immediately loaded into the editing frame so you can rename it there.

**Comment by KayRJay** [comment]
Roger.  I should have said all of the above was predicated on a rather long template name.

"Over and out" on this topic!
