### ISSUE TITLE
New Analysis features

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#489]
Less than five minutes using the new features so far, but looks good!

One suggestion already ... don't start plotting or graphing until there is something to graph.  My first flight was in Sept 2018, so I have eight months of zero to the left on the graph and on the top of the chart.   All those zeros are not very interesting to be sure!

**Comment by ericberman** [comment]
Very much by design.  I always align year-month buckets on January because the label spacing is every 12 months and it looks really weird to have the labels every august (where you can't even see the new year boundary).

**Comment by ericberman** [comment]
Note that I actually do a pass to figure out the buckets, then I pad from there.  For years, no padding needed - it's from the earliest flight to the latest flight.  But for year-month, everything looks messed up if you don't align to January.  So I find the earliest flight, and then start from Jan 1 of that year.

**Comment by KayRJay** [comment]
Well, different strokes for different folks.  

In the same way, who says weeks must begin on a Sunday (or a Monday)?   It’s all arbitrary.  

I could want to see my monthly totals since my first solo, or since I got my PPL.   Any specific date (or the first date for which there is data) is just as good as any other arbitrary date like Jan 1.

Maybe a nice option would be to allow the user to specify a date range for Analysis, which would be (always?) a subset of range of dates of the flights in the current result set.
