### ISSUE TITLE
Do we need CustomProperties field in logbook query?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#497]
can be big.  Used for general text queries, but only has title of property and any string value.  add colon and formatted value too?  Or just kill it?

**Comment by KayRJay** [comment]
I kinda like the idea of custom properties.  Generally, it seems beneficial to give the user flexibility.   Would they be private to the user, or public?

Are you suggesting by "add colon and formatted value" that the string could contain xxxx:<string value>  yyyy: <string value> and you'd support searching on xxxx or yyyy?   Is that any better than just doing a string search?  Or are you suggesting something else?

**Comment by ericberman** [comment]
This is totally a non-functionality related issue.  I wonder if I'm pulling in a column in the database query that I don't need to pull in, or that is redundant.  I'm not proposing anything that would change any functionality.

The idea behind adding the colon value is that if you have, say, "Solo time: 1.3" you could then search for "Solo time: 1.3" in the general text query (something that doesn't work today).  The main challenge there is formatting - e.g., if someone uses hh:mm format, then it should be "Solo time: 1:18", and if they're in France using decimal it would be "Solo time: 1,3"  I used to pass down localization/preferences information to the database in order to do a bunch of that at MySQL, but ripped that out a few years ago in favor of JSON-ified properties, which gave both a performance boost and let me move the localization/display preferences to the UI where they belong.

I *think* that the "CustomProperties" column in the field is now orphaned and redundant, which means it's just slowing the query down and making results bigger than needed; that's what this issue is tracking.

**Comment by KayRJay** [comment]
Seems reasonable to just kill this.  The user would search for the solo time as a property value, not as a text string.   Unless I'm just not understanding.   

If no one is using the CustomProperties field, then there's no harm done.   What would you do with the data if some people are using it?   Concatenate with the "Comments" property?

Seems cruel to kill an orphan, rather than find him/her a new home, but ...

**Comment by ericberman** [comment]
No, you're not understanding.  I'm not talking about killing any columns in a table or merging anything or removing data.  I'm talking about killing a computed (GROUP_CONCAT) column in a result set of a query, if it is in fact obsolete (which I *think* it is).

**Comment by KayRJay** [comment]
oh, it’s an internal thing.   Never mind my comments then!

**Comment by ericberman** [comment]
Turns out that I am using this for flightquery, but by reformatting it slightly I can enable property: value searches.  E.g., "Safety Pilot: Joe Smith" (even with the quotes, per issue #471)  So there's that...  But searching with specific values can still be difficult because of hh:mm or regional variations.
