### ISSUE TITLE
Flights with Dual Time but no CFI should be raised as an "issue" when checking flights

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#541]

**Comment by ericberman** [comment]
You mean no CFI name?  I'm reluctant to raise that as an issue.  Typically the flight is signed, which provides the name (i.e., it's not required as a field).  And for old imported logbooks (e.g., from paper), the instructor's name is long forgotten.  This can lead to a whole lot of noise.

But for unsigned flights, I suppose it's reasonable...

**Comment by KayRJay** [comment]
I don't know about "typically".  I only know about my own flights.  I have a CFI in every flight that has dual time, whether signed or not.

**Comment by ericberman** [comment]
Are they not signing the entries in your logbook?  they certainly should be...

**Comment by KayRJay** [comment]
They are ,… in a paper log book.  I don’t ask them to sign MyFlightBook.  Even if I did ask, whether or they did o, it seems quite reasonable to have their name recorded in MyFlightBook.

**Comment by ericberman** [comment]
That would be an unsigned flight.  I'm willing to flag those.

**Comment by ericberman** [comment]
But they should sign in MyFlightbook! :)

**Comment by KayRJay** [comment]
Realistically, that's not necessarily going to happen.  What about people who have old logbooks they  recorded in another e-logbook?  Or people who have paper log books they want to replicate in MyGFlightBook?

Even for flights that are SIGNED, isn't it reasonable to have the name (not a signature) recorded as a searchable (and checkable) attribute?

**Comment by ericberman** [comment]
Reasonable?  Absolutely.  Something to warn about?  Whooboy, people have a LOT of flights with Dual, many will have the instructor's name int he signature or otherwise not there.  This can be a LOT of noise.... But I think letting people know for UNSIGNED flights is reasonable.  By definition, if it's signed, I have the instructor's name.

**Comment by KayRJay** [comment]
And if it is not signed, then you (I) don’t have the instructor’s name.

I recently had a few flights with a different CFI.  I don’t know if I’ll ever fly with him again. I'm simply not going to to ask him to go back and sign in MyFlightBook, as he has signed in m paper logbook.  He's old school, and uses a paper log only.

Because it is up to the user to decide whether or not to fix an “issue” MFB might flag, I don’t see the downside in raising as an “issue” flights where Dual was received and there is no instructor name. 

I don’t see a lot of noise with the policy I advocate.  I do see some rigidity in the policy you want.  

I get that a signature is more important for the FAA than it is for me, personally.  On the other hand, when it comes down to it, I’ll likely show both the hard copy and MFB logs to the FAA … and they should be consistent.  If the CFI hasn’t literally signed in MFB, at least I can show the FAA the CFI’s name matches what’s in the paper logbook.

**Comment by ericberman** [comment]
Where exactly are we disagreeing?  I'm proposing flagging an issue if (a) there is Dual time indicated, (b) there is no instructor name, and (c) the flight is not signed.

**Comment by KayRJay** [comment]
Then we are not disagreeing.   I didn’t understand that was your position from the earlier comments.  

Under which condition would you flag flights with Dual Time ...

- Both instructor name AND signature are absent?
- Or one is present, but the other is not?

Seem both are present is not a warning condition but the others are.

**Comment by ericberman** [comment]
Nope.  If NEITHER is present.  I.e., no way for an observer to determine the instructor name. May be in comments, but I can't determine that.

**Comment by KayRJay** [comment]
Ok, I can live with that.  If BOTH are absent, it’s flagged. 

Now if I had a way to find those flights that were signed, but the instructor name was missing, then I could manually fix them by recording the CFI name separately from the signature.  But I don’t think that’s currently possible.

The problem is still that even if all my flights are signed, but the instructor name is blank/missing (for some flights), I can’t find flights where the CFI was Ed or Pete or someone else or none of the above. Unless I could search for signatures by / not by a given CFI ...

**Comment by ericberman** [comment]
If the flight is signed, then the instructor name - by definition - is not missing (it's present in the signature).

Indeed, I don't currently search by signature.

**Comment by KayRJay** [comment]
Then you don’t address my need/desire to search on instructor name ...

**Comment by ericberman** [comment]
You can still add the Instructor Name property if you want to search on that.

**Comment by KayRJay** [comment]
But I can only search for an instructor by "text" if I understand properly, not on the "Instructor name" property.   And, I believe I cannot find flights that don't have a value for "Instructor name".

Thanks for adding the check for unsigned flights with Dual time.   That makes sense.   

But, since you can't search signatures, don't you think it would be useful to provide a "Check flights" function to identify flights that are signed, but don't have an "Instructor name"?  People could ignore that warning if they wish.   Or this kind of check  could be in a new category of "less important warnings" or something, and other "less important" warnings might arise over time.

**Comment by ericberman** [comment]
Actually, just looked at the code: if you search for "Joe Smith" and Joe Smith signed your flight, that will in fact be hit.

**Comment by KayRJay** [comment]
That's nice.  

But what about my comments of 2 hours ago?

**Comment by ericberman** [comment]
That addresses the comments.  I added the check for unsigned flights.  And if you search for your instructor's name, it will match in either the Instructor Name property OR if they signed your flight.  What did I miss?

**Comment by KayRJay** [comment]
These comments:
- Can't search for a Dual time flight _without_ an instructor (named or signed).
- There isn't a Check flight(s) option to look for such flights.
- Having a category of "less important warnings".

**Comment by ericberman** [comment]
Check Flights will report dual time without an instructor.  That's the check-in above.  (And I did update the website now).

I don't know what "less important warnings" is.  These are all - by definition - not important.  I don't understand the purpose of distinguishing degrees of unimportance.

**Comment by KayRJay** [comment]
I tried it and I have a ton of such flights.  I gotta do a bulk update of some sort for just those flights.     It does work too, when adding or updating a flight.  Thank you.

i guess you put that check in the "Additional (uncategorized) issues" , which is fine.

**Comment by ericberman** [comment]
Yeah, I did too - I did a bulk update this morning to cut down on that noise. :)
