### ISSUE TITLE
Document how Text searches work

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#545]
Currently, the Search page permits text searching with the field labelled "Text of flight contains ...".
However, there is no help to let people know what that means.  It could be in a blog, I suppose, but it would be more convenient and more widely seen if it were documented in place with a [?].

Given the features implemented in #471, "Text contains" is a little misleading/incomplete.  Better might be just "Search text in flights [?]".

The [?] tip should explain what "text" means.  I assume it is all non-numeric values, or at least such things as comments, airports (airport names?), tail numbers, names (passengers, CFIs etc.), etc..

The [?] tip should also explain how to write a text search, as you document in issue #471.  It should mention case insensitivity, and the following rules:

- dog cat = must contain "dog" and must contain "cat" (but not necessarily in that order, separated by anything)
- "dog cat" = must contains "dog cat" (inclusive of spaces)
- dog OR cat = contains dog OR contains cat
- -dog = must NOT contain dog
- -"dog cat" = must NOT contain "dog cat"
- -"dog -cat" must NOT contain "dog -cat" (i.e., the hyphen inside the quoted text is preserved, not negation)
- -dog -cat = contains neither dog nor cat ("NOT dog AND NOT cat") - so there is no negation of an "OR", since this can express that.
- -dog OR cat = doesn't contain dog OR does contain cat.

It's almost grep, but probably easier for most people and likely sufficient.  I suppose I could want a "grep mode" or an "Advanced mode" like in MS Word, but that's not necessary.

**Comment by ericberman** [comment]
Already documented in the FAQ at https://myflightbook.com/logbook/Public/FAQ.aspx?q=63#63

**Comment by KayRJay** [comment]
Not complete, even in the FAQ, as there is no mention of the above rules, nor a description of which fields are text-searchable.

And a person has to be diligent enough to scroll to the bottom of any page to even find the FAQ, then scroll through all the questions to "Tips for searching".

Are you unwilling to update the FAQ with the above rules, and perhaps put a [?] tip near the text search field saying "Read the FAQ for tips on searching"?  Doesn't seem like I'm asking for much.

**Comment by ericberman** [comment]
I didn't close the issue because I'm going to add a [?] tip, which will link to the FAQ.
BTW, I think the FAQ does cover all of the rules above; you're just enumerating various combinations, and that's obviously an unbounded set of possible combinations.

 * dog cat = covered
 * "dog cat" = covered
 * dog OR cat = covered
 * -dog = covered
 * -"dog cat" = redundant - this is just combining rules above
 * -"dog -cat" = redundant, just combining rules above (except for the fact that the hyphen is inside.)
 * -dog -cat = redundant, just combining rules above
 * -dog OR cat = redundant, just combining rules

And the general text field actually does search for any text, values, etc.

**Comment by KayRJay** [comment]
Thanks for adding the [?] tip.

The FAQ is helpful, but perhaps you could update it to say"There is also a field where you can search for general text, _which includes comments, airports, names, etc."_

While you are certainly write about what is covered or redundant, it wouldn't hurt to add a few more examples, covering the less obvious combinations.
