### ISSUE TITLE
Add "Check this flight" to Logbook drop-down menu

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#551]
<img width="257" alt="Screen Shot 2020-03-22 at 6 17 49 PM" src="https://user-images.githubusercontent.com/16978320/77267836-8069ba80-6c69-11ea-963e-eb986d02e8c7.png">
... otherwise, to check an existing flight I have to open it for editing, then scroll down, then press the icon.  I'm big on saving user clicks!

**Comment by ericberman** [comment]
I get that, but if you're in the list view, rather than going 1-by-1 to check flights, why not just go to Logbook->Check Flights?  Saves even more clicks if the flight in question has no issues...

**Comment by KayRJay** [comment]
Yeah-but ... why not?  Seems a simple and "nice" thing to do for users ... I can check flights that I may recently entered, and I might be concerned only about them.
