### ISSUE TITLE
For fun: Put a graph of daily flights taken (and pilots flying) over time on the home page

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#553]
In these crazy times, it would be very interesting to see how flying activity has changed over time.   A graph on the home page of the number of flights taken each day over a variety of periods on the home page would cause me to visit the home page more often.  

You could also chart the number of pilots reporting flights each day.  Both metrics could be on one chart (using the left and right vertical axes).

The chart could appear as a selectable alternative to, or above or below the image that you display.

The standard stock price chart would be a good model:

<img width="875" alt="Screen Shot 2020-03-23 at 11 03 56 AM" src="https://user-images.githubusercontent.com/16978320/77342618-13503680-6cf6-11ea-8f92-671868ef6907.png">

I'm assuming you're cooped up too, with time on your hands, looking for things to do or distract you, but hopefully healthy!  😀😷

**Comment by ericberman** [comment]
Interesting suggestion.  I like the pictures there, since they change, so I wonder if it doesn't work best to create an image and put that in the slideshow...

**Comment by KayRJay** [comment]
An image wouldn't be interactive.   It would be fun and interesting to be able to choose a recent period (the last n days/months, etc. as in the stock chart), or choose an arbitrary period (like Sept 1-30, 2001).

A chart like the could also be used to show the number of landings at a given airport.

Maybe, if and when you get to publishing more info on airports (issue #448), you'll want a page for things like this.

**Comment by ericberman** [comment]
Right, but an interactive chart means separate real estate - either below the fold, or pushing the images down.  A static image can share real estate.

I'm also a bit concerned about offering that sort of detailed information.  I show aggregate numbers today, that's also not accidental.  A static image would let me pick the level of aggregation I'm willing to share.

**Comment by ericberman** [comment]
See Issue #445 for my hesitation about getting too granular on this data.

**Comment by KayRJay** [comment]
It would be a real shame to do this particular chart with no interactivity.  That's part of the fun of this whole thing.  

I mostly understand your concerns about confidentiality especially of the number of users.   What other things would you like to keep confidential? 

You could limit date ranges, whether trailing ranges like on the stock chart or interactive with a user-provided date range.  You might require ranges to be nothing shorter than a week (or a month), or cover a period more than a year ago.   You could limit the degree of aggregation, without making the chart really static.

Additionally, the chart is really only useful to show trends, not actual numbers.  There need be no scale on the y-axis, and you wouldn't have to pop up details for a given period (like you do in Analytics).  So, the data would only be visual, and still would be aggregates.  

You could limit the number of different charts a user could request per week, or have a limit of 10 charts an hour or something like that.

All of these things would restrict the amount of information a competitor could get about your user base.  I'm not sure there really would be much risk of leaking confidential information.

Perhaps this chart could be placed in an entirely new area on the site.  For example, I could imagine a new top-level menu button ("FUN STUFF") that goes to a page with
- information about airports (ala #448)
- information about flight activity: numbers of flights, pilots, flights at airports, flight durations, numbers of airports visited per flight, interesting flight types (military, agricultural, aerobatic, etc.)
- information about pilots: percent (not the number) who are students, VFR / IFR / ATP, % in each US state or world country, average number of type ratings per pilot, etc.
- information about aircraft: % by types/categories, make/model, advanced, with steam or glass avionics, etc., etc.,
- "Believe it or Not" - longest flight, most airports visited, most flights/month or /year, etc.
- social networking tools (e.g., find a pilot via tail number, pilot name, airport, image, public flight, location, etc. or send email via MFB, etc.)

By the way (and I'm sure it's obvious), you could compute almost all this info once/day as part of your nightly batch job.  The only one that would require a live query would be the interactive chart.    

I suppose you could even compute a set of charts once/day, and allow the user to choose among them.  There could be a set of date ranges you supply, rather than allowing the user to specify arbitrary ranges.   We'd not even know if they were truly interactive.  This is also a good way to limit the disclosure of confidential information.

**Comment by ericberman** [comment]
So I think at the moment I've done what is reasonable to do on this issue.  If there are other interesting stats to propose, let's do those in individual github issues.
