### ISSUE TITLE
While exporting pdf in EASA format the name of PIC is duplicated in column 7 "Name(s) of PIC" and in column 12 "Remarks and Endorsements"

### ISSUE THREAD

**Issue by A-Bag** [ericberman/MyFlightbookWeb#571]
![image](https://user-images.githubusercontent.com/32464041/78531529-e156ce00-77e5-11ea-8750-30736f133f0f.png)

**Comment by A-Bag** [comment]
The name of PIC in column 12 "Remarks and Endorsements" is reduntant.

**Comment by ericberman** [comment]
Fix implemented, will be live in a day or two.
