### ISSUE TITLE
add google authenticator or Microsoft authenticator as optional 2-factor auth?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#573]

**Comment by ericberman** [comment]
Or simply email: on new device, send an email with a code.

**Comment by jeremyericksonmcp** [comment]
I just downloaded GitHub to use as a Microsoft Authenticator but I have no idea what I'm supposed to be doing in GitHub to allow this to work. Can you point me in the right direction? Thanks!

**Comment by ericberman** [comment]
I haven't had a chance to do any investigation on this; sounds like you're already ahead of me! :)

**Comment by ericberman** [comment]
https://www.c-sharpcorner.com/blogs/google-authenticator-in-asp-net shows some nice easy .net code.  Gotta figure out how to work into the flow, though.

**Comment by ericberman** [comment]
More high-level background.  I'm going to create a separate branch to implement this.
https://www.freecodecamp.org/news/how-time-based-one-time-passwords-work-and-why-you-should-use-them-in-your-app-fdd2b9ed43c3/

**Comment by ericberman** [comment]
Two remaining questions:
a) how (or if) to integrate 2FA into the mobile apps.  Kinda by definition, if you have access to the phone you probably have access to the authenticator app, so probably punt on this.
b) lock account after too many failed 2FA attempts?  Probably no need - already have password, and hard to do a brute-force attack.

**Comment by ericberman** [comment]
Need to use 2FA to turn off 2FA, probably to change email too.
