### ISSUE TITLE
Add site-wide statistics about MyFlightBook usage on the About ... Page

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#589]
As mentioned in issue #588, it might be interesting to provide summary information about recent site-wide use of MyFlightBook somewhere.   The About MyFlightBook page seems a good place.

This might include

- the number of flights
- number of pilots who added flights
- total flight time of those flights
- number of aircraft and models of aircraft added
- number of new airports
- number of airports visited across all pilots adding flights

or any other statistics you think are interesting.

The data you present might only (and always) be the past 7 days and past 30 days, and would be as of the prior midnight.  By fixing the rolling time period to 7 and 30 days, you wouldn't need to adjust the beginning of the year or a month. 

This idea is for when you have some "extra" time on your hands.  😀

**Comment by ericberman** [comment]
Great idea; done (same as what's on home page, since that's the key data that I have or can easily compute).  Will be live when I next update the site.
