### ISSUE TITLE
Can't upload KML file from FlightAware ...

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#605]
I was able to upload (attach to an existing flight) a recent FlightAware track log (from 5/17), but not one from 5/5.

<img width="425" alt="Screen Shot 2020-05-23 at 2 03 01 PM" src="https://user-images.githubusercontent.com/16978320/82739642-5a5ea600-9cfe-11ea-93ed-ec93d44d451e.png">

[FlightAware_N262WH_KHCR_KHCR_20200505.kml.zip](https://github.com/ericberman/MyFlightbookWeb/files/4672444/FlightAware_N262WH_KHCR_KHCR_20200505.kml.zip)

**Comment by KayRJay** [comment]
Dunno why, but it worked the next time I tried it ...

**Comment by ericberman** [comment]
I can't reproduce this - it uploaded fine for me. 

Was the issue that you uploaded the .zip file perhaps?

Note, by the way, that there is a decent amount of KML that I can't parse.  I should be able to attach it, though (and certainly shouldn't give errors!) - but I can't make heads or tails out of it.  KML is a crazily unstructured format...

**Comment by KayRJay** [comment]
Nope, I uploaded the zip after the failure.   Didn’t re-download the KML file either.  

The KML may be crazy, but so was my actual flight!

**Comment by ericberman** [comment]
:)
Crazy flight is fine.  KML's problem is that there isn't a well defined schema.  I want to answer a simple question: "where is the path, including time-stamped / speed decorated position reports."  There is quite literally no deterministic way to answer that, it's just a series of heuristics.
