### ISSUE TITLE
Improve data entry (and deletion) of telemetry files, add name of file if it exists

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#608]
I have two flight segments for which I have two (FlightAware) telemetry files.   I somehow managed to upload one, but I want to delete it, so I can merge the two files and then upload.   I realize that uploading a file deletes an existing file, but there are cases where it is necessary to delete a telemetry file without replacing it.

Also, it would be helpful if the name of an existing telemetry file was displayed on the details page (above the map?) and also on the edit page.  Something like this:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/16978320/82768521-cc151d80-9dec-11ea-963a-74c50b6920b2.png">

**Comment by ericberman** [comment]
I don't have the name of the original file anywhere, so I can't display it - and 90+% of the time, there is no file name (the vast majority of telemetry comes from people recording it on their phones/tablets, in which case there is no file).  And extension only loosely corresponds to file type anyhow); you can see what kind of file the original data is by going to the details page (click on the date of flight:
![image](https://user-images.githubusercontent.com/16455286/82772448-01713980-9df4-11ea-9a99-5f7421a5daf0.png)

You can already delete telemetry without replacing it:
![image](https://user-images.githubusercontent.com/16455286/82772341-bd7e3480-9df3-11ea-9567-9d7bb86b0ee1.png)

So I think the functionality requested here (other than preserving original file name) already exists.

**Comment by KayRJay** [comment]
Thanks.  Somehow I didn’t see that.
