### ISSUE TITLE
Minor telemetry issues and suggestions

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#614]
Please consider some small changes, as follows:

Change the wording from "Add new data" to "Replace" if there is existing data (unless you do support multiple telemetry files.

Provide a way to view existing telemetry (by going to the Detail page) if there is some.  Currently, one has to go back to the list view and select the paper clip.  This format would work:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/16978320/83981552-31ccd380-a8dc-11ea-9e86-c66e233678ae.png">

The tabs on the Flight Details page (which shows the telemetry) should be sticky, rather than always go to "Chart".

At the top of the page, there's "Return to List View", which is helpful.  It would be handy to also have "Return to edit this flight" (although the drop-down menu has "Edit" of course, but that's a bit more clicking and moving of the mouse.

**Comment by ericberman** [comment]
The paper clip is already clickable to go to the detail page.  It opens in a new tab, so there's no need for return-to-edit this flight.  (Even if not, the back button would work fine).
I've changed the wording to "Replace".  Also replaced "Delete" with a red-x.

**Comment by KayRJay** [comment]
Ah, now I see the paper clip.  However, it’s near the “Learn more” link, so I didn’t see it, having read the text “This flight has associated data”.  

Visually, I think my approach would be more clear.  It would at least be preferable to move the paper clip to follow that text.   (Yes, I get that the paper clip and the text are redundant, and neither appears if there is no telemetry.)

By the way, I didn’t realize a new tab would be opened, because I viewed the flight on a page opened by a “pinned” tab, and didn’t see that a new tab would open.  Thanks for the tip re the Back button too.

**Comment by ericberman** [comment]
I also made the "this flight has data" label clickable.

**Comment by KayRJay** [comment]
Did you elect "no fix" for the idea of making the tabs on the Flight Details page sticky, rather than always go to "Chart"?

**Comment by ericberman** [comment]
Yes, or "by design", if you will.  If you click on date of flight, it goes to the summary page of the flight details (it's "home" page); if you click on the paper clip, it goes to the chart, which serves as the "home" page for the telemetry portion.  I definitely do NOT want to go to raw data - that's often very large and makes the entire page sluggish, so I want that to be on-demand only.

**Comment by KayRJay** [comment]
Fair enough.
