### ISSUE TITLE
Minor enhancement to Find Airports page

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#615]
Currently, on the Flight Details page, clicking "Airport Information" takes you to the AC-U-Qwik page for the airport.   However, there's no similar link on the "Find Airports" page.    

Since the main function of "Find Airports" is indeed to get information about an airport, it seems logical to link to the relevant page on AC-U-Qwik from there.

**Comment by ericberman** [comment]
Huh.  The main function of find airports is to look up codes ("What's the ICAO for London Heathrow?"), but indeed, no reason not to add the link.
