### ISSUE TITLE
Telemetry bug?  Missing end time or landing airport

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#616]
After adding a FlightAware telemetry file (attached) to a new flight, with no other data, I click Autofill, and the following fields are filled in: date, departure airport, engine start and stop times, and the flight start time.  However, the landing airport is not filled in, nor is the the flight end time.

From the Raw Data, I see that the last sample shows a non-zero computed speed, so perhaps the plane was still in the air.  However, MyFlightBook indicates that the engine was turned off as of the time of the last sample.   A probable case is that the plane landed at that time, and there was no telemetry after that.   It's inconsistent to record "Engine Stop" and not make a similar assumption about the landing airport based on the lat/long reported.  Or, there should not be a recorded "Engine Stop" time.

MyFlightBook seems to find an airport near the lat/long reported in the first sample in the telemetry, but doesn't do the same for the last reported lat/long?
[FlightAware_N262WH_KAPC_KMCC_20200513.kml.zip](https://github.com/ericberman/MyFlightbookWeb/files/4743207/FlightAware_N262WH_KAPC_KMCC_20200513.kml.zip)

**Comment by ericberman** [comment]
That's exactly it.  The data here had no speed provided, so I inferred it, and the last sample had a computed speed of 113kts.  So you were still airborne, as far as I could tell.

Engine stop here essentially just means "here endeth the data"; I *know* it is a final point of sample, and I compute things like total time based on engine (by default), so I need that boundary.  But the flight ended...unknown.  And the flight landed...who knows where, and who knows how much later?  It was airborne as far as I can tell.  But the samples ended, so I can record that the total flight was at least 0.39 hours.

I do the best I can with the data I'm given but I generally am conservative about not filling something in unless I am sure that it's accurate.
