### ISSUE TITLE
Enhance club reporting

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#619]
Currently, a manager can get a report of all flights in any aircraft by any pilot.   He can limit the range of dates, but not the particular aircraft or pilot.

Something like this would work:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/16978320/84105816-b4d25480-a9d6-11ea-8a82-5cff04fe2bc4.png">

... or a regular expression could be used for the aircraft ID and pilot name.

**Comment by ericberman** [comment]
Yeah, I can see filtering on aircraft and/or pilot.  I don't think contains or exclusion correspond to any real club use case.  I'm just using a drop-down for pilot and a dropdown for aircraft.

**Comment by KayRJay** [comment]
Admittedly I am not a true club manager, but you proposed I use a club to record use of my plane by others when I am not on board.    Maybe I am the only person in the world who would lend his plane to a friend (and non-club manager)  who doesn't use MyFlightBook.   Maybe not. 

I still have a problem.  There isn't a way to record a flight with the name of the perhaps several different people who used my plane.   At the moment, I can only record a flight under my "alias" account.    So, I can't filter for just the flights where Joe or Pete was commuting in or borrowing my plane.

If there were even a single other property .... Pilot Name ... that I could enter with the flight, and then filter on in in the club report, I'd be good.   (Even just exposing the comment field as searchable by a club manager would work for me.)   As is, I think I will have to just enter the flights under my alter ego account, and not use the club feature at all.  

As to whether the "not" and "contains" criteria correspond to "real club use case" ... that may be a line call.   If it does make sense to filter for flights by a specific pilot or aircraft, why would it not be reasonable to do the opposite?   I'm generalizing something that apparently does make sense.  I don't see the harm in such generalization.  Your decision ... and it is of course your decision! ... precludes the possibility that some real world club manager would want to use the "not" or "contains" criteria, even though you've never heard of that requirement.

Now, if I were suggesting full generalized search capability within the club reports (being able to pick any searchable attribute as in the logbook search page), that would be a different matter.  Possibly a lot of work, possibly not.  But if it makes sense for a user to base a query on (almost) any arbitrary property for his own flights, perhaps it makes sense for a club manager to do so for flights by club members.   

I can imagine that clubs may have policies about how club planes can be used, and the club reporting could help a manager determine if a member violated those policies.  Here are some scenarios where a club manager might want a more comprehensive search (and reporting) feature.  He might want to see use of the plane where the flight was:

- longer than x hours
- in IMC
- XC for >= x miles 
- had >=x number of landings
- passengers
- etc

These may not be real-world use cases you've seen.   (Of course haven't seen ANY real-world use cases).  But, maybe they do exist and no one ever took the time to ask for support for such scenarios.

But, I am not suggesting you  actually implement a fully generalized approach.  I'm "thinking out of the box" and using my imagination.  Over time, you might want to consider expanding the club manager's set of features.  

You invited me to use the club feature in part because I might have some useful suggestions, I think.  I hope at least some of this is useful to you and real world club managers.

**Comment by ericberman** [comment]
So for the scenario: you aren’t using a club as a club.  You’re using it as a way to keep track of who is flying your plane without you, so it’s already a bit of a hack.  Your specific use case was “I want to see all the flights my aircraft made, whether or not it’s by me”.  The club report does that neatly, which is why I suggested it.  Once you say “I want to see flights not by me”, then the club has lost its value as a hack for this and I say “you’re already entering these flights into the second account, why not log in there and you can see then.”  Alternatively, you can create a share link from that account so that you don’t have to sign in/out of the other account.  So perhaps I am not understanding the use case here.

If you have multiple pilots you can distinguish them by “name of PIC” property.  But again, I think at that point the club starts to wane as a useful hack, as you suggest.

I can see a club manager wanting to narrow by aircraft (perhaps for insurance, or just to see who In the club are putting the hours on the aircraft), and narrow by user (e.g., a member calls up with a question about their bill).  I don’t see obvious corresponding use cases for “all but” user/aircraft.

The other use cases you suggest may indeed exist; I assume I’ll hear of them at some point if they do.

**Comment by KayRJay** [comment]
>  Your specific use case was “I want to see all the flights my aircraft made, whether or not it’s by me”.

Actually not.  Per my first note on this topic: 

> It would be nice if I could easily find flight I was not on. 

So, not "whether or not".

The use case for me is to "see all the flights by people I lend the plane to (and without me on board)".  Ideally, I'd see it in full detail, as I can in the Logbook.   So, as you say, the club isn't useful to me as a hack.  

I sent a share link from one account to another, but that doesn't really help.  I specifically don't want to add a flight I was not on to my personal log book.  Nor does this allow me to generate a report of all flights by Joe or Pete.  I can do all that in the alias account, and there's no real need to avoid the sign in/out.

I entered the PIC, but the club report lists my "alias" as the "Pilot Name".  If the PIC attribute overrode / took precedence over the name of the MyFlightBook user, I think I can use the club feature, otherwise not.

As to my imagined use cases ... I don't know how you source requirements or use cases.  I once suggested you actively solicit feature requests, either by a survey or poll or some other way.  You may be surprised.  It takes considerable effort to ask for something that doesn't exist.  I hope you do eventually hear from club managers about what they'd like.

**Comment by ericberman** [comment]
If the goal is simply to find a flight you were not on, then the 2nd account is the right way to go; the club functionality is not a good fit for that.  I misunderstood.

**Comment by KayRJay** [comment]
Fair enough.

I can find the flights having "NONE" of Dual time, PIC or CFI time.  That does the job.
