### ISSUE TITLE
Created a flight from telemetry, edited it, telemetry is recorded, but no paperclip icon in the logbook

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#624]
Used the playpen to create a (pending) flight from a telemetry file.  After editing the flight to add some comments, added the flight.  The flight is in the logbook, but there is no paperclip icon.   The telemetry is available on the detail page though.

[FlightAware_N262WH_KHCR_KSLC_20200620.kml.zip](https://github.com/ericberman/MyFlightbookWeb/files/4810381/FlightAware_N262WH_KHCR_KSLC_20200620.kml.zip)

**Comment by ericberman** [comment]
I'm not able to reproduce this, at least not as described.  It seems I'm not keeping the telemetry at all.  But I can't get it to show up in the logbook with a missing paperclip and view details.  So that's definitely a bug, but it's different from what you describe.

**Comment by KayRJay** [comment]
See these ...
<img width="896" alt="Screen Shot 2020-06-21 at 6 12 11 PM" src="https://user-images.githubusercontent.com/16978320/85238395-cc540900-b3ea-11ea-936d-b46cf3b7fd82.png">

<img width="972" alt="Screen Shot 2020-06-21 at 6 12 24 PM" src="https://user-images.githubusercontent.com/16978320/85238391-c827eb80-b3ea-11ea-926e-6a78bb6e7842.png">

**Comment by ericberman** [comment]
I don't see any telemetry there - blue line is airport-to-airport.  Telemetry is always red.  Note at the top of the details page: you have "Flight" and "Aircraft", but no Chart, Raw Data, or download.

So the issue isn't the missing paper clip - that's correct, since the flight has no telemetry.  The issue is the missing telemetry.   It's a bug in the playpen page (i.e., it's not attaching the telemetry when it saves the pending flight).

**Comment by KayRJay** [comment]
Aha.   It’s worked in the past … wonder what’s up?!

**Comment by ericberman** [comment]
From bulk-create-from-telemetry?  It works if you add telemetry to a pending flight...

**Comment by KayRJay** [comment]
Just one telemetry upload from here: https://myflightbook.com/logbook/playpen/BulkImportFromTelemetry.aspx <https://myflightbook.com/logbook/playpen/BulkImportFromTelemetry.aspx>

By the way, it would be nice if the time zone were sticky …

**Comment by ericberman** [comment]
Ha!  Just took a look at the code in bulkImportfromtelemetry, and saw this:
// TODO: Save the flight data?  Perhaps de-sampled for size?

So yes, I am indeed (currently) creating the flight and tossing the data.

Note that if the data results in an empty flight, I ignore it; I'm going to keep that functionality.

**Comment by KayRJay** [comment]
Thanks.
