### ISSUE TITLE
Spelling Correction: Dead Reckoning

### ISSUE THREAD

**Issue by mstonespeedy** [ericberman/MyFlightbookWeb#660]
"Ded." and "ded." should be "Dead" and "dead" for the flight property and corresponding help tip:

- Navigation by Pilotage and Ded. Reckoning
- Indicates that the flight included ded. reckoning

**Comment by ericberman** [comment]
Really?  I know that [Wikipedia](https://en.wikipedia.org/wiki/Dead_reckoning) disagrees with me, but only until 1931, but I had always understood it to be short for "deduced reckoning".  Sorta how (Kitty Corner)[https://www.gingersoftware.com/content/phrases/kitty-corner/] derives from Cat Corner which is actually a corruption Quatre corner.

**Comment by ericberman** [comment]
For fun, let's take a poll!

**Comment by mstonespeedy** [comment]
Very interesting! Thank you. I didn't know that.

Anyway, I'm mostly interested in how I need to log my cross-country flights according to FAR Part 61:

https://www.ecfr.gov/cgi-bin/retrieveECFR?gp&r=PART&n=14y2.0.1.1.2#se14.2.61_11

**Comment by ericberman** [comment]
Whooboy, cross-country.  that's a related but different disaster.  See [this blog post](https://myflightbookblog.blogspot.com/2018/08/logging-cross-country-time.html); the answer is that it matters for what you are logging it.

BTW, poll on facebook is already decidedly towards "Dead".

**Comment by mstonespeedy** [comment]
Yes, I agree that cross-country flights are a separate and larger issue. I have general questions about that, but not to be answered here.

I opened this issue simply to address the spelling of "dead reckoning" based on FAR 61. I'm really not sure which spelling I would choose, solely considering my own preference. I'd have to research that a bit more before deciding.

Obviously, this is up to you to decide. But either way, I'm sincerely grateful for the very interesting discussion. :)

**Comment by ericberman** [comment]
FB poll is unanimous: Dead.  Property fixed.
