### ISSUE TITLE
Add [?] tip for searching for arrival and departure airports with !

### ISSUE THREAD

**Issue by KayRJay** [ericberman/MyFlightbookWeb#693]
Currently, the [?] tip for _text_ searches refers to the FAQ for tips on searching, but there is no tip for airport-based searches.  All search criteria other than airport searches either have explicit parameters or a tip.   

Users may not ever discover the ability to search for arrival or departure airports (issue #327), because it is much more likely that they'd search using an airport query than a text query.

It makes sense to include a [?] tip for searches using airports, and not just a general reference to the FAQ's searching tips:
![Screen Shot 2020-11-14 at 2 50 44 PM](https://user-images.githubusercontent.com/16978320/99157723-cc4df180-2688-11eb-9516-2a8c5ac11f79.png) 
It would be more clear for the tip to indicate that the arrival/departure search works _only_  in airport searches, not text searches:
![Screen Shot 2020-11-14 at 3 09 06 PM](https://user-images.githubusercontent.com/16978320/99158010-5bf49f80-268b-11eb-9c82-3d42e4a17f34.png)
The arrival/departure search feature is useful, but is hidden deep in an FAQ.  Subtlety is one thing, but total obscurity is another!

**Comment by ericberman** [comment]
Actually, this is mentioned in the search tips, but I added clarification in the FAQ for the fact that it only applies in the airports field, and I added a tooltip for just this point next to the airports field itself (not the "click to show/hide" text, since if it's collapsed then the tip doesn't add any value).
