### ISSUE TITLE
Add ability for instructor to modify student flights that they have signed.

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#696]

**Comment by ericberman** [comment]
Only, of course, if they also have "Add" permission in the logbook.

**Comment by ericberman** [comment]
Actually just realized that there's already an "Edit" link if your name is on the flight (either due to a "please sign" request, or because you've previously signed it).  Only thing is that you don't have access if it's got a valid signature (but if valid signature, why do you need to re-sign?)  So I think I will "won't fix" this except possibly to make access a bit more visible.

**Comment by JPSloan1** [comment]
The use case for me is I've added and then signed a flight (as instructor) into my student's logbook, and then I realize I did not completely log some specific requirement, so I want to go back and update the comments to reflect that requirement. So I'd want to "edit" after I've signed (and then re-sign if required).

**Comment by JPSloan1** [comment]
So maybe make it possible to access "edit" if I have a valid signature, but the change invalidates the signature and I have to re-sign it? Or let me "un sign" so I can see the "edit" ?  Or just let me modify it if I'm the one that signed it?

**Comment by ericberman** [comment]
Where things get complicated was in passing down the fact of your privilege to add flights; doing that requires a database call, so things get a little messy, but what I think I'll do is just let you re-sign a flight with a valid signature (normally, it doesn't give you that option).  If you do that, the edit button will show up, so you can do the edit and sign all in one step.  Actually cleaner that way in the end, but it means doing a bit of work to carry the privilege state to where it needs to go.

**Comment by JPSloan1** [comment]
ok. so if I view the student's logbook I'd see a "sign this entry" link even if I've already signed it, and then in that sign flow I see the edit link?  Seems fine to me.   But actually I just went to try to sign an unsigned flight and don't see the "edit" link at all -- does that only appear when the student sends for signature? Not when I click "sign this entry" from his logbook?   Or maybe not when I'm the one that created the entry in the first place?

**Comment by ericberman** [comment]
Sorta.
 * [Existing functionality, unchanged] If they request a signature from you (regardless of whether they have given you permission to view their logbook), then your name is already attached to the flight for which they requested the signature.  That is implied permission to edit that flight, and you can edit it as part of the signing process.
 * [Existing functionality, unchanged] If they've granted you permission to view their logbook and they've modified a flight that you've signed (i.e., invalidated the signature) then you can re-sign it AND edit it, if you like, as part of the re-signing process.
 * [Existing functionality, unchanged if "Add" permission is not granted] If they've granted you permission to view their logbook, then you can already go in and sign any random flight you see that is either unsigned, or which has an invalidated signature (yours or another CFI's).  But you can't edit them unless they've already explicitly requested your signature for that specific flight (i.e., the 1st scenario above).  Signing is "as-is", and once signed, you can't edit it.  Any flight that has a valid signature doesn't even show the option for you to do anything to it.

What I'll do is modify the 3rd scenario here slightly so that if a flight is (a) signed, (b) by you, (c) still valid, and (d) they gave you "add" permission, you re-sign that flight and edit it in the process

**Comment by ericberman** [comment]
The matrix here is crazy complex... There's also the whole issue of instructors signing "ad-hoc" (fingernail scribble rather than having a relationship).  Working through it...

**Comment by ericberman** [comment]
OK, I think I have a slightly clunkier but cleaner model (and one that removes all of the complexity/danger from mucking with the matrix of permissions.)

IF you are viewing a student's logbook and (a) you have permission to add to that logbook, AND (b) there is a flight that you have signed for which the signature is still valid (i.e., underlying flight has not been modified in any ways that are treated as meaningful by the system), THEN you can click "Remove Signature".

Doing this mostly (but not entirely) removes the signature.  Rather, it sets it as unsigned but pending a signature from you.  I.e., it will show up in your list as if the student had requested that you sign it. 

This, of course, makes sense - you removed the signature, you want to remember that you should re-sign it at some point.

But then it can piggyback on the existing functionality that lets you edit a flight for which the student has requested a signature *from you*.

So to edit a flight you've signed your steps would be:
 * Remove the signature
 * Now click to re-sign it.  The edit option will be available to you, and (better still) will be integrated with the signing process.

**Comment by ericberman** [comment]
Have some more testing to do, but can likely check this in tomorrow.

**Comment by JPSloan1** [comment]
OK, seems reasonable to me. Appreciate the responsiveness!

**Comment by ericberman** [comment]
Have some more testing to do, but can likely check this in tomorrow.
