### ISSUE TITLE
Feature idea - easy insert of training items.

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#705]
Whooboy…I get where you’re coming from, but that’s anything but a simple feature to add.

Not least is the fact that I currently support something like 111 ratings across FAA, Transport Canada, EASA, CASA, and others.   (Wow, I hadn’t counted until just now, but yep, it really is one hundred eleven!  And I have a new one – Canadian night rating - on my to-do list for this week…).  So the sheer number of things to enumerate is large.  Granted many of these share many requirements, but not 100%.

So I’m seeing 3 possible feature ideas here:
•	As you say, a drop-down from which you can pick a rating area and tick off checkboxes for the things you need to include (could possibly add boilerplate directly to the comments for the student).  This is, IMO, the most doable/tractable thing here.
•	A standardized way to record this stuff so that the student can demonstrate where they received each required training.  This is significantly harder.  For one, much of what needs to be logged is typically put into comments, which means parsing free-form text and trying to ensure you do it correctly (in the face of misspellings or small deviations from the “standard” text, which often isn’t as standardized as people think).  Or, I could create properties for these things, which  is deterministic but requires people to know that they’re there and to log them appropriately.
•	In ratings progress, could enumerate the required endorsements and see which ones you have and which ones remain, so that you remember which you need to give before sending the student for their checkride.  Some similar issues here – I can look for keywords like FAR references, but many of the required FAR references cover multiple ratings, or you can use free-form templates, or it’s the freeform part that is where you fill in that it’s for the AMEL rating vs. the ASEL rating, or the endorsement was given physically.

I think # 1 above might be the most doable, and helps with standardization so that searching is easier.  Still a ton of work to gather that information for (soon to be) 112 different ratings, though, but it could be something where the feature just grows over time as I add more data.

If I were to do it, I think I’d do it not in the regular flight-editing screen, but rather in the sign-a-flight screen.  I.e., the entry can have whatever it has, but when you go to sign the flight, you could tick off the things you do and it would attach that to the CFI’s comments.  

From: James 
Sent: Saturday, November 21, 2020 11:45 AM
To: MyFlightbook <myflightbook -at- gmail.com>

It's not necessarily endorsements but the underlying training.  Yes, I can create a templated endorsement saying I have provided the required training under FAR 61.65(c), but each item of that training must actually be logged as well -- somewhere in a logbook entry that I have signed it must say "flight solely by reference to instrument with loss of primary flight instruments," or whatever.  And in addition to those logbook entries and endorsement, some DPEs want a summary of that training that is more detailed than the endorsement, but less detailed than every single logbook entry. 

So the first feature could be something just like templated properties where as I'm creating a logbook entry, I could say "show me all the required regulatory items under 61.65(c)" just as I can create other log entry templates, and then I can check which ones we covered during the flight. I have created my own list of these and it's pasted below. 

The second feature could be something like "create a summary of every flight that involved an item from 61.65(c) and give me the dates and total time by item." A simple version of this could just be searching the same way you can search and view totals for flights with certain properties today. 

61.65(b)(1) | Aeronautical   knowledge | Federal   Aviation Regulations of this chapter that apply to flight operations under   IFR
-- | -- | --
61.65(b)(2) | Aeronautical   knowledge | Appropriate   information that applies to flight operations under IFR in the “Aeronautical   Information Manual”
61.65(b)(3) | Aeronautical   knowledge | Air   traffic control system and procedures for instrument flight operations
61.65(b)(4) | Aeronautical   knowledge | IFR   navigation and approaches by use of navigation systems
61.65(b)(5) | Aeronautical   knowledge | Use of IFR   en route and instrument approach procedure charts
61.65(b)(6) | Aeronautical   knowledge | Procurement   and use of aviation weather reports and forecasts and the elements of   forecasting weather trends based on that information and personal observation   of weather conditions
61.65(b)(7) | Aeronautical   knowledge | Safe and   efficient operation of aircraft under instrument flight rules and conditions
61.65(b)(8) | Aeronautical   knowledge | Recognition   of critical weather situations and windshear avoidance
61.65(b)(9) | Aeronautical   knowledge | Aeronautical   decision making and judgment
61.65(b)(10) | Aeronautical   knowledge | Crew   resource management, including crew communication and coordination
61.65(c)(1) | Prelight   preparation | Pilot qualifications
61.65(c)(1) | Prelight   preparation | Weather Information
61.65(c)(1) | Prelight   preparation | Cross-country flight planning
61.65(c)(2) | Preflight   procedures | Airplane Systems related to IFR Operations
61.65(c)(2) | Preflight   procedures | Airplane Flight Instruments and Navigation Equipment
61.65(c)(2) | Preflight   procedures | Instrument Flight Deck Check
61.65(c)(3) | Air   traffic control clearances and procedures | Compliance with Air Traffic Control Clearances
61.65(c)(3) | Air   traffic control clearances and procedures | Holding Procedures
61.65(c)(4) | Flight by   reference to instruments | Instrument Flight
61.65(c)(4) | Flight by   reference to instruments | Recovery from Unusual Attitudes
61.65(c)(5) | Navigation   systems | Intercepting and tracking navigational systems and arcs
61.65(c)(5) | Navigation   systems | Departure, en route, and arrival operations
61.65(c)(6) | Instrument   approach procedures | Nonprecision approach
61.65(c)(6) | Instrument   approach procedures | Precision approach
61.65(c)(6) | Instrument   approach procedures | Missed approach
61.65(c)(6) | Instrument   approach procedures | Circling approach
61.65(c)(6) | Instrument   approach procedures | Landing from an instrument approach
61.65(c)(7) | Emergency   operations | Loss of Communications
61.65(c)(7) | Emergency   operations | Approach with loss of primary Flight Instrument indicators
61.65(c)(8) | Postflight   procedures | Checking instruments

**Comment by JPSloan1** [comment]
Another way to do it could just be to create/align the flight properties with the appropriate reg. For some of the maneuvers and subject areas, "maneuvers - power off stalls" for instance, there is already a property. If I could be sure that all the properties existed to cover all the required maneuvers and aeronautical knowledge areas for a certificate or rating, I could create my own templated logbook entry with the properties I want. 

A nice to have would be if the properties including the applicable reg (61.87(d)(10) for stalls) but of course that could be complicated with lots of ratings that could include that maneuver.

But that said I know you probably don't want more proliferation of properties.

**Comment by ericberman** [comment]
Yeah, that would mean an absolute explosion of properties.  I'm reluctant to go that route.  Plus "the appropriate reg" changes over time, and isn't consistent across jurisdictions.  Lots of users outside the US, so I'm super reluctant to tie general maneuvers to FARs.

**Comment by ericberman** [comment]
At this point, I think it's a data issue.

**Comment by ericberman** [comment]
Allow for contains search rather than just prefix.  E.g., so you could type "short" or "short-field" (could treat the hyphen as a word separator for "contains both") and find all of those tasks.  Might make the boldfacing match harder, but can just nix that; it's not super valuable.
