### ISSUE TITLE
Add a way to attach information to airports?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#721]
Link to a common file share or FB feed or similar?

**Comment by jg-gatech** [comment]
A flight has a Select File box that allows me to attach 0..* photos or any other file type. I suggest the same thing for airports, allowing me to attach 0..* files. Adding a Comments field to airports would also be nice.

**Comment by ericberman** [comment]
Added support for pirep.io; let them handle it.

**Comment by jg-gatech** [comment]
Hi Eric,

I think adding support for pirep.io is an ideal solution. But I don't see
how to access it from MyFlightbook. Are instructions posted somewhere?

Thanks,
Jeff

**Comment by ericberman** [comment]
Go to Airports->Routes and type in a route and you'll see Airport Guide links at the bottom.

**Comment by ericberman** [comment]
Just realized it's not showing up when you click on your route for a flight.  I'll fix that.
