### ISSUE TITLE
maxing out memory - are videos or other large uploads ever loaded into memory?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#781]

**Comment by colinmcfadden** [comment]
@ericberman Is this the crashing issue causing you to need to recycle the app pool?

**Comment by ericberman** [comment]
Thanks for the pointer.  Indeed, this is what causes me to recycle the app pool, and it's random - I'll go weeks or months without any problem, then boom.

Wouldn't a profiler in production slow things down?

**Comment by colinmcfadden** [comment]
Yeah that's the tough part. The fact that it takes long periods of time to occur, it is clearly a slow leak and makes it difficult to stress test.

It certainly can, especially the really detailed ones like dotTrace. Not sure about CodeTrack but I've heard good things. The only other thing I would recommend is a memory dump of w3wp after at least a week or two has gone by without the out of memory exception, and we could analyze it offline.

**Comment by ericberman** [comment]
I've gone over the code with a fine toothed comb to find any case where there are IDisposables, and there aren't.  That coupled with the fact that I can't seem to reproduce this in a dev environment leads to my suspicion is that it's not a memory leak per se but something that is perhaps dependent on user input.  E.g., someone uploading a 10GB video and me trying to load it into memory.  (Of course, I've checked that).  

It's also possible that it's 3rd party code.  E.g., my code doesn't load the video into memory, but the Amazon Elastic Transcoder code to which I upload it might have a bug into it.  Or, another similar example: when I added support for MGRS coordinates in Issue #774, I used CoordinateSharp.  Worked fantastic on my machine, but when I brought it to the live site, it brought the system to its knees.  Turns out it would do all sorts of greedy calculations each time I tried to create a coordinate, which was negligible load (and no leak!) on a test environment but even light load would slam the CPU (subsequent fix took out a global flag to turn that off and performance became stellar again).

But either way, it doesn't seem to be gradual, which is what you'd expect with a true leak.  I think there's something acute...

**Comment by ericberman** [comment]
The other issue I periodically see is a runaway pegged CPU.  Every few months or so.

**Comment by colinmcfadden** [comment]
You have a staging/test environment don't you? I'm wondering if throwing a profiler on there might be a good idea, and we could try to break it in there. If it's a slow leak, we might be able to see it over time, and perhaps we can get it to spike with more demanding actions in the UI (i.e. testing 3rd party code). Even with ultra light load, we might be able to pick up trends over time. Long shot, and if it's acute that likely won't help, but it's going to be really difficult to find if we don't know what is executing when the crashes occur.

**Comment by colinmcfadden** [comment]
And you're on aws correct?

**Comment by ericberman** [comment]
Yes, i have a staging environment.  And I'm on Google Cloud.  I should indeed install codetrack on it.

**Comment by colinmcfadden** [comment]
Okay cool, I do know Google Cloud has a profiler as well, but I'm unsure of costs related if any.

Probably a dumb question but have you ever had a user report the site was down or hung up while they were using it? Or are you usually the one that catches it?

**Comment by ericberman** [comment]
Usually me, but I have been notified on Facebook.  Google has monitoring so I get notified pretty quickly if it's nonresponsive.

Generally the most common reason for the site going down is me taking out an update.  Otherwise it will go for weeks on end without problems..

**Comment by ericberman** [comment]
Also high CPU hitting

**Comment by ericberman** [comment]
Caught one in the wild.  This doesn't look like a memory leak, where I'd expect a slow steady monotonic increase in memory utilization - this is a spike in both CPU and memory, requiring a reboot of the VM (task manager end-task on IIS didn't work)
![image](https://user-images.githubusercontent.com/16455286/134013925-37cb16f4-4606-437e-9277-c20640b79166.png)

But otherwise, you can see from the graph that memory is flat flat flat for days/weeks at a time.

**Comment by ericberman** [comment]
Another issue that can arise: Antimalware Service Executable (Windows Defender Service) has runaway CPU - seems to happen after doing large save-to-PDF (see issue #836) - could be related?

**Comment by ericberman** [comment]
Another thought - am I ever growing the cache too large, not using expiration reasonably?  (e.g., with images?)  I wonder if this is arising from a crawler here and there pounding the site - which should be fine - but causing thrashing due to massive cache bloat, causing cache swapping and reloading (which would impact CPU too...)

**Comment by ericberman** [comment]
<img width="1309" alt="Screen Shot 2021-09-30 at 11 11 43 AM" src="https://user-images.githubusercontent.com/16455286/135514130-72766ee0-22fb-46bf-98e9-b6eb02057260.png">
Clearly not a secular memory leak - this is vicious and focused.  Possible DOS?  Still wondering if PDF generation is the issue...

**Comment by ericberman** [comment]
One other theory, but a weak one: crawlers hitting "allmakes.aspx" are filling the cache (and memory) with image info.  Bit of a longshot, but could explain why it's only periodic.  Allmakes now explicitly uncaches every image.  Also made all caching calls specify a timeout and got editairports out of the cache altogether (properly belongs in session object).  Still something demonic hiding under the surface...

**Comment by ericberman** [comment]
I don't think this could possibly account for the dramatic spike in memory, but I think it is a potential memory leak: CreateRSA in OAuth2AuthorizationServer.cs is IDisposable but not wrapped in a using.  Any way to tell when we can dispose of it?

**Comment by ericberman** [comment]
At this point, I think memory leak per se may be a red herring.  Possible there's some CPU-intensive operation I'm not seeing that is allocating a ton of memory, which either would be released after some point exceeding the machine's current config, or which due to an infinite loop of some sort never gets a chance to be released?  Not sure how to track something like that down...

**Comment by ericberman** [comment]
New hypothesis: not a memory leak at all or an infinite loop.  Rather that there's a deadlock or race condition...somewhere.

**Comment by ericberman** [comment]
![image](https://user-images.githubusercontent.com/16455286/145687870-f735d28d-f685-407c-8cdd-cd4502ede8dc.png)
Turned on automatic recycling...

**Comment by ericberman** [comment]
Memory leak is, at this point, a symptom, not a cause, I belive.
Meantime, tweaked automatic recycling: 
![image](https://user-images.githubusercontent.com/16455286/145687900-a04733b7-4e57-4431-a289-f71c3e97bdb7.png)

**Comment by ericberman** [comment]
The recycling conditions above seem to be doing a good job with this.  It's a band-aid, not a solution, but it's solving the problem and I'm out of other ideas.
