### ISSUE TITLE
Feature request: Copy photos directly to a flight on the website interface

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#794]
Use copy paste
Same as Google Photos

**Comment by ericberman** [comment]
Is this copy/paste of a file (i.e., go to Windows Explorer, find IMAGE001.JPG and copy that)?  Or copy/paste of the image itself (e.g., open the image in Paint, select a region, and copy that)?  

There may be security issues with the former.

**Comment by zartom** [comment]
Right click an image on a website + Ctrl+ V

**Comment by ericberman** [comment]
ahh, so not uploading from your computer but from somewhere on the web

**Comment by zartom** [comment]
Yeah from Facebook, google photos and such
Although draggin and dropping a file from a local folder is also a wanted behavior

**Comment by ericberman** [comment]
dragging/dropping a file from local folder is the current behavior.

**Comment by ericberman** [comment]
Just played with this into google photos.  Looks like it is indeed image on the clipboard - e.g., go into paint, select a region, and paste.

**Comment by ericberman** [comment]
https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c
