### ISSUE TITLE
Stuttering UI when changing block time and total time is set to be block time

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookWeb#798]
In preferences I've changed the total time to be equal to Block time. Once I've done that and I'm editing the block (out or in) in a specific flight, it is very slow (the time spinner movement). I guess it is because it update the total time and SIC and X-country time fields in real-time and not just after I press the ok button

**Comment by ericberman** [comment]
Moving to the Android issues list.  https://github.com/ericberman/MyFlightbookAndroid/issues/234
