### ISSUE TITLE
OAUTH2 Refresh Token seems to expire too early

### ISSUE THREAD

**Issue by wizardoff** [ericberman/MyFlightbookWeb#854]
The OAUTH2 access token has a two-week expiration. 
Trying to refresh the token using the refresh_token within a few days works, however seems that after about a week (i.e. while the access token is still unexpired) the refresh does not work anymore, returning "error":"invalid_grant".
Trying to refresh after the access_token has expired (i.e. after more than two weeks) returns the same error.

**Comment by ericberman** [comment]
Hmm....just took a quick look at the code, not seeing any expiration at all on the refreshtoken.
I just tried using the oauthclienttest tool in the playpen (which has a minor bug I need to fix - the "Refresh Token" button doesn't work unless you first use the access token to get something), with the access token lifetime set to 2 minutes.  So about 5 minutes after getting an accesstoken, it was expired - indeed, doing a getcurrency call failed.  But refresh token worked.

Can you send the code that shows how you're doing your refresh?

**Comment by wizardoff** [comment]
Below is the code - written in Google Javascript. I have a few users who are in this strange situation where the access_token is still valid, but can't refresh - I can send you the details offline.

`function mfbRefreshToken_(refresh_token) {
  var url = 'https://myflightbook.com/logbook/OAuth/oAuthToken.aspx';
  var payload = { 
      'refresh_token': refresh_token,
      'client_id': 'xxx',
      'client_secret': 'yyy',
      'grant_type': 'refresh_token',
      'redirect_uri': 'https://script.google.com/macros/s/xxxx/exec'
    };
  var header = {
    method: 'POST',
    payload: payload,
    muteHttpExceptions: true,
  };
  
  var response = UrlFetchApp.fetch(url, header);

  responseText = response.getContentText();

  newTokens = JSON.parse(responseText);

  updateTokens_(newTokens.access_token, newTokens.refresh_token);
}`

**Comment by ericberman** [comment]
Finally had some time to look into this.  I *think* I’ve found where I can set the refreshtoken duration.  (I wrote this code a while ago, and so I’ve forgotten how the whole architecture works).

In the oAuth flow, you (browser) navigate to https://myflightbook.com/logbook/member/oAuthAuthorize.aspx, where the user is shown the screen asking to grant permissions for the various requested scopes.  When they say “Yes”, I store an authorization in the database, and THERE I specify an expiration that (at the moment) is 14 days.  

The user is then redirected back to you, and you make the server-to-server call to me to issue the authtoken.  That code (to issue the authtoken) is all buried in the bowels of the DotNetOpenAuth compiled code, so I can’t look at that, but it calls to me:
(a)	see if you are authorized to get a token, and if so, 
(b)	to create an access token with a distinct expiration that I specify.  

In the check for (a), if you’re after the expiration of the authorization, I return “no” and subsequently (b) never happens.  

So I just tried modifying things  where I leave the authorization valid for a year, but set the accesstoken to expire in one minute.  I get an access token, works great.  I wait a minute, and the access token fails.  BUT…if I hit “refresh token”, it goes through. 

But I think that will solve it, and then I won’t need access to the private authtoken (which is a good thing).

I assume 1 year on the refresh token is fine, with a 14-day expiration on the accesstoken?

**Comment by ericberman** [comment]
Will take fix live probably tomorrow.

**Comment by wizardoff** [comment]
Awesome!
This certainly explains the phenomena, and why the errors I saw were not specifically saying the refresh token has expired.
Thanks for looking into this and fixing it. I will report in a couple of weeks (when the new tokens will expire) if everything still works fine.

**Comment by ericberman** [comment]
Actually did a 10-year expiration on refresh tokens, so effectively forever.
