### ISSUE TITLE
Feature request: allow instructor to upload pdf/image to student endorsements.

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#869]

**Comment by JPSloan1** [comment]
Potentially two separate stories: 
As an instructor, I can *view* the uploaded image/pdf endorsements for a student who has given me permissions
As an instructor, I can *upload* image/pdf endorsements for a student who has given me permissions

**Comment by ericberman** [comment]
Student can control this:
 * "Can view my logbook" grants/revokes permission to see endorsements issued by other instructors and any scans that were uploaded
 * "Can add flights to my logbook" grants/revokes permission to upload additional scans.  (You always have the ability to add a digital endorsement.)
