### ISSUE TITLE
Custom Currency not matching on private aircraft notes

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#880]

**Comment by fkrauthan** [comment]
For more details on this:  I just created a flight for today with `C-FCAP`. The plane has as private note `#PFC#` but when using that in my custom currency rule `Pacific Flying Club - 60 Day Currency` it does not show up anymore.

**Comment by ericberman** [comment]
Yep.  found the issue.

**Comment by ericberman** [comment]
Try it now.

**Comment by fkrauthan** [comment]
Perfect. Works now :)

**Comment by ericberman** [comment]
BTW, I should have suggested: you could also have edited the custom currency rule to include multiple specific aircraft.  Probably would have worked just as well...  The advantage, though, of the #PFC# is that if you add a new aircraft, you don't need to update the rule.

**Comment by fkrauthan** [comment]
Yeah I initially had that. But the club has lots of planes so was hoping for an easier system (and the adding private note is exactly that) :)

**Comment by ericberman** [comment]
I think I'm going to back out this change and ask you to name specific aircraft in your custom queries.  Looks like the addition of private notes to the database query increases the execution time by 10-20x for large logbooks.  It shouldn't - everything is indexed, but since the workaround is easy (just edit the rule if you need to change the set of aircraft), I think I'll back it out.  

Otherwise, I'm seeing people who get timeout errors when they try to view their currency.  That's significantly worse.

**Comment by fkrauthan** [comment]
Which then brings me back to an ask to figure out a way to simplify it in case I have a lot of planes in my flightbook as the current way of managing planes is very error prone in that regards (if I forget to hold down shift I clear all my selection when tying to add a new plane). Maybe the plane selection can be changed to a two list approach with "+" and "-" button to add/remove?

**Comment by ericberman** [comment]
If you accidentally forget to hold down the shift key, you can hit cancel and try again.

I will do some investigation as to why the query slows down so dramatically when pulling in the private notes, but obviously getting currency to NOT time out is the priority here.

**Comment by fkrauthan** [comment]
Yeah totally understand it. I also just reverted my currency back to individual planes in case you want to disable it right away.

**Comment by ericberman** [comment]
Actually just figured it out how to eliminate the database penalty.  Not sure *why* it's faster, but it is.  Will take it live Sunday

**Comment by ericberman** [comment]
oh, wait...it's a little faster, but not by much on the larger logbooks.  Will continue to investigate, but will need to go to individual planes if I can't figure out how to make it faster.

**Comment by ericberman** [comment]
Another option requires more code; it's probably the better option.  I'll look up private notes separately - that way if you have 4000 flights mostly in the same aircraft, I'm not potentially repeating the private notes so much anyhow.  This would not be a sunday fix though.

**Comment by fkrauthan** [comment]
Yeah Like adding a new field `Plane Private Note Contain` then you could load all planes based on that and plug that into the logbook search (similar as if I would have selected them all).

**Comment by ericberman** [comment]
Adding that level of specifity makes the UI way too complicated.  I almost always have a cache of your aircraft in memory, so I can just write code to look it up there.  Doing that *might* result in an extra database call (to fetch your aircraft), but almost never since it's generally already in memory.  It's just a little bit slower (when looking at a flight, need to retrieve the aircraft from the cache rather than just looking at the private notes associated with the flight), but should be negligibly so.  Bigger issue is that it means writing code (rather than just accessing data), so it's not something I want to do in my 12 hours at home Saturday night/sunday morning before heading back on the road.  It's something I can do later next week.

**Comment by fkrauthan** [comment]
But you potentially have to load ALL flights in a time period instead of potentially only half of them? I guess the question comes down to: is it cheaper todo a quick aircraft search (in memory or via DB) and then do the flight search potentially reducing the number of returned results OR loading always all possible flights and then filter them inside code.

**Comment by ericberman** [comment]
No.  All currencies always look at all flights.
