### ISSUE TITLE
Feature Request: API

### ISSUE THREAD

**Issue by mpearon** [ericberman/MyFlightbookWeb#905]
I’m a ForeFlight user, but would love to use MyFlightbook as another place to log my data - one that is a little more accessible.  I’m currently parsing the ForeFlight logbook export, and would love an endpoint to send that data to.  Do you have any plans for something like this?

**Comment by ericberman** [comment]
Pretty rich API already available.  See https://myflightbook.com/logbook/Public/Developer.aspx and https://www.youtube.com/watch?v=q8fIDXWP9TU

**Comment by mpearon** [comment]
Noted! I guess I hadn't done enough research.
I haven't played with oAuth yet, so I'll take a swing at it! Thank you for the guidance.

**Comment by ericberman** [comment]
By all means let me know if you have any questions.  myflightbook@gmail.com

**Comment by ericberman** [comment]
Also note that I can import foreflight files more or less directly already.
