### ISSUE TITLE
Cloud Storage: put backups into a yyyy-mm folder to reduce clutter?

### ISSUE THREAD

**Issue by ericberman** [ericberman/MyFlightbookWeb#910]

**Comment by Anticept** [comment]
Mainly what happens, is that in the example of google drive, one big folder has an impact on performance when browsing the folder. Separating them into dated subfolders would change the game a lot!

**Comment by Anticept** [comment]
I love what you did @ericberman but, one small little thing...

I would prefer each dated folder to be in a subfolder of "myflightbook", rather than creating folders at the root of my cloud storage :)

![image](https://user-images.githubusercontent.com/521038/162026608-9471c8dd-9c12-464c-ae69-1c0f9a8d70a1.png)

**Comment by ericberman** [comment]
I do that on OneDrive and Dropbox because they both let me specify a full path and it will create all of the intermediate folders as necessary.  I explicitly chose NOT to do that on Google Drive because I can't do that without a lot of back and forth.

E.g., on OneDrive and Dropbox the effective conversation is:

- Put a file at MyFlightbook\yyyy\month\filename.csv.

One call, one result.  If any of the 3 folders above didn't already exist, they do now.

To do that on Google Drive, the effective conversation would have to be:
 - See if the "MyFlightbook" folder exists.
 - If it doesn't exist, create it.
 - Enumerate its children, looking for a "yyyy" folder.
 - If it doesn't exist, create it.
 - Enumerate its children, looking for a month folder
 - if it doesn't exist, create it.
 - Now put the file into that folder

I really, really, really do not want to do that: not only does it exponentially increase the odds of a timeout or an error or similar, but it also greatly increases the latency with all of the back-and-forth network calls.  Especially at night when I'm doing hundreds of backups for people, that can really slow down the process.

**Comment by Anticept** [comment]
I went to look at the API docs, and ooof, I can see that there isn't a a nice clean way to do this.

The closest thing I can think of is for myflightbook to remember the folder ID when it was created, and only recreate if it throws an error.

Regardless, this is a relatively minor issue at this point, you've been super helpful already!
