### ISSUE TITLE
Feature: Sign flights in bulk

### ISSUE THREAD

**Issue by omercnet** [ericberman/MyFlightbookWeb#953]
After importing lots of flights (because you discovered this amazing app too late!) one would like to have their CFI sign all the flights in their new logbook so it's valid for the license

**Comment by ericberman** [comment]
OK, so here's how I'm doing it.  If an instructor goes to view flights for a student that are awaiting signature, when they go to sign one of their flights if there are additional flights awaiting signature, then a "Sign and go to next" option will be visible.  When you click that, it signs the current flight and then shows the next unsigned flight awaiting signature.
