### ISSUE TITLE
Add "pause" feature for custom currencies

### ISSUE THREAD

**Issue by fkrauthan** [ericberman/MyFlightbookWeb#984]
I was wondering if there is any chance to have an easy "disable"/"pause" checkbox on a custom currency to be excluded from emails and UI till re-enabled.

My use-case for that is for example if you rent planes from a local school. But plan to take a pause from that but might plan to return there at some point. There is no need to keep being notified that your currency has expired but I would save myself the setup of re-creating the custom currency if I can just disable it. And from a performance point of view It shouldn't have any hit.

**Comment by ericberman** [comment]
can probably just have an enable/disable flag
